preds = \
{'Akron': {'Alabama': '33%',
  'Arizona': '18%',
  'Arkansas': '27%',
  'Auburn': '19%',
  'Baylor': '19%',
  'Boise St': '21%',
  'Bryant': '51%',
  'Chatt': '31%',
  'Colgate': '49%',
  'Colo St': '22%',
  'Connecticut': '23%',
  'Creighton': '31%',
  'CS Fullerton': '52%',
  'Davidson': '22%',
  'Delaware': '43%',
  'Duke': '22%',
  'Georgia St': '51%',
  'Gonzaga': '19%',
  'Houston': '23%',
  'Illinois': '22%',
  'Indiana': '35%',
  'Iowa': '25%',
  'Iowa St': '30%',
  'Jville St': '54%',
  'Kansas': '16%',
  'Kentucky': '19%',
  'Longwood': '52%',
  'Loyola-Chi': '30%',
  'LSU': '33%',
  'Marquette': '33%',
  'Memphis': '29%',
  'Miami FL': '30%',
  'Michigan': '28%',
  'Michigan St': '28%',
  'Montana St': '56%',
  'Murray St': '25%',
  'N Mex St': '32%',
  'Norfolk St': '57%',
  'N Carolina': '30%',
  'Notre Dame': '34%',
  'Ohio St': '29%',
  'Providence': '26%',
  'Purdue': '21%',
  'Richmond': '33%',
  'Rutgers': '30%',
  'S Dakota St': '35%',
  'San Diego St': '29%',
  'San Fran': '23%',
  'Seton Hall': '32%',
  "St Mary's": '25%',
  "St Peter's": '55%',
  'TAM C. Christi': '55%',
  'TCU': '31%',
  'Tennessee': '20%',
  'Texas': '30%',
  'Texas Tech': '21%',
  'TX Southern': '57%',
  'UAB': '25%',
  'UCLA': '22%',
  'USC': '25%',
  'Vermont': '36%',
  'Villanova': '20%',
  'Virginia Tech': '31%',
  'Wisconsin': '25%',
  'Wright St': '53%',
  'Wyoming': '32%',
  'Yale': '51%'},
 'Alabama': {'Arizona': '44%',
  'Arkansas': '51%',
  'Auburn': '48%',
  'Baylor': '47%',
  'Boise St': '51%',
  'Bryant': '64%',
  'Chatt': '55%',
  'Colgate': '57%',
  'Colo St': '49%',
  'Connecticut': '49%',
  'Creighton': '53%',
  'CS Fullerton': '60%',
  'Davidson': '50%',
  'Delaware': '62%',
  'Duke': '50%',
  'Georgia St': '62%',
  'Gonzaga': '37%',
  'Houston': '49%',
  'Illinois': '46%',
  'Indiana': '60%',
  'Iowa': '52%',
  'Iowa St': '53%',
  'Jville St': '58%',
  'Kansas': '39%',
  'Kentucky': '43%',
  'Longwood': '58%',
  'Loyola-Chi': '50%',
  'LSU': '49%',
  'Marquette': '50%',
  'Memphis': '53%',
  'Miami FL': '52%',
  'Michigan': '50%',
  'Michigan St': '48%',
  'Montana St': '63%',
  'Murray St': '50%',
  'N Mex St': '59%',
  'Norfolk St': '66%',
  'N Carolina': '57%',
  'Notre Dame': '56%',
  'Ohio St': '54%',
  'Providence': '59%',
  'Purdue': '46%',
  'Richmond': '50%',
  'Rutgers': '52%',
  'S Dakota St': '58%',
  'San Diego St': '53%',
  'San Fran': '48%',
  'Seton Hall': '58%',
  "St Mary's": '41%',
  "St Peter's": '66%',
  'TAM C. Christi': '66%',
  'TCU': '55%',
  'Tennessee': '38%',
  'Texas': '50%',
  'Texas Tech': '45%',
  'TX Southern': '67%',
  'UAB': '53%',
  'UCLA': '49%',
  'USC': '55%',
  'Vermont': '49%',
  'Villanova': '40%',
  'Virginia Tech': '49%',
  'Wisconsin': '51%',
  'Wright St': '62%',
  'Wyoming': '58%',
  'Yale': '65%',
  'Akron': '66%'},
 'Arizona': {'Arkansas': '62%',
  'Auburn': '54%',
  'Baylor': '45%',
  'Boise St': '53%',
  'Bryant': '71%',
  'Chatt': '64%',
  'Colgate': '71%',
  'Colo St': '55%',
  'Connecticut': '57%',
  'Creighton': '54%',
  'CS Fullerton': '69%',
  'Davidson': '63%',
  'Delaware': '72%',
  'Duke': '48%',
  'Georgia St': '70%',
  'Gonzaga': '45%',
  'Houston': '48%',
  'Illinois': '56%',
  'Indiana': '67%',
  'Iowa': '67%',
  'Iowa St': '59%',
  'Jville St': '70%',
  'Kansas': '56%',
  'Kentucky': '48%',
  'Longwood': '67%',
  'Loyola-Chi': '65%',
  'LSU': '52%',
  'Marquette': '54%',
  'Memphis': '55%',
  'Miami FL': '68%',
  'Michigan': '57%',
  'Michigan St': '54%',
  'Montana St': '64%',
  'Murray St': '63%',
  'N Mex St': '69%',
  'Norfolk St': '72%',
  'N Carolina': '64%',
  'Notre Dame': '70%',
  'Ohio St': '59%',
  'Providence': '59%',
  'Purdue': '52%',
  'Richmond': '61%',
  'Rutgers': '59%',
  'S Dakota St': '66%',
  'San Diego St': '50%',
  'San Fran': '60%',
  'Seton Hall': '61%',
  "St Mary's": '50%',
  "St Peter's": '64%',
  'TAM C. Christi': '70%',
  'TCU': '55%',
  'Tennessee': '47%',
  'Texas': '56%',
  'Texas Tech': '51%',
  'TX Southern': '66%',
  'UAB': '66%',
  'UCLA': '54%',
  'USC': '67%',
  'Vermont': '58%',
  'Villanova': '53%',
  'Virginia Tech': '64%',
  'Wisconsin': '52%',
  'Wright St': '70%',
  'Wyoming': '65%',
  'Yale': '74%',
  'Akron': '81%',
  'Alabama': '55%'},
 'Arkansas': {'Auburn': '40%',
  'Baylor': '38%',
  'Boise St': '48%',
  'Bryant': '69%',
  'Chatt': '60%',
  'Colgate': '67%',
  'Colo St': '55%',
  'Connecticut': '44%',
  'Creighton': '51%',
  'CS Fullerton': '69%',
  'Davidson': '57%',
  'Delaware': '68%',
  'Duke': '37%',
  'Georgia St': '67%',
  'Gonzaga': '34%',
  'Houston': '41%',
  'Illinois': '43%',
  'Indiana': '68%',
  'Iowa': '53%',
  'Iowa St': '58%',
  'Jville St': '67%',
  'Kansas': '32%',
  'Kentucky': '32%',
  'Longwood': '67%',
  'Loyola-Chi': '55%',
  'LSU': '46%',
  'Marquette': '51%',
  'Memphis': '55%',
  'Miami FL': '66%',
  'Michigan': '55%',
  'Michigan St': '50%',
  'Montana St': '68%',
  'Murray St': '61%',
  'N Mex St': '65%',
  'Norfolk St': '68%',
  'N Carolina': '55%',
  'Notre Dame': '65%',
  'Ohio St': '56%',
  'Providence': '51%',
  'Purdue': '34%',
  'Richmond': '58%',
  'Rutgers': '58%',
  'S Dakota St': '55%',
  'San Diego St': '49%',
  'San Fran': '50%',
  'Seton Hall': '59%',
  "St Mary's": '38%',
  "St Peter's": '69%',
  'TAM C. Christi': '68%',
  'TCU': '51%',
  'Tennessee': '36%',
  'Texas': '48%',
  'Texas Tech': '43%',
  'TX Southern': '68%',
  'UAB': '62%',
  'UCLA': '45%',
  'USC': '62%',
  'Vermont': '61%',
  'Villanova': '35%',
  'Virginia Tech': '59%',
  'Wisconsin': '51%',
  'Wright St': '70%',
  'Wyoming': '62%',
  'Yale': '74%',
  'Akron': '72%',
  'Alabama': '48%',
  'Arizona': '37%'},
 'Auburn': {'Baylor': '42%',
  'Boise St': '54%',
  'Bryant': '71%',
  'Chatt': '67%',
  'Colgate': '69%',
  'Colo St': '54%',
  'Connecticut': '57%',
  'Creighton': '52%',
  'CS Fullerton': '70%',
  'Davidson': '63%',
  'Delaware': '69%',
  'Duke': '55%',
  'Georgia St': '70%',
  'Gonzaga': '46%',
  'Houston': '53%',
  'Illinois': '56%',
  'Indiana': '74%',
  'Iowa': '68%',
  'Iowa St': '69%',
  'Jville St': '69%',
  'Kansas': '46%',
  'Kentucky': '46%',
  'Longwood': '69%',
  'Loyola-Chi': '67%',
  'LSU': '59%',
  'Marquette': '61%',
  'Memphis': '65%',
  'Miami FL': '67%',
  'Michigan': '61%',
  'Michigan St': '57%',
  'Montana St': '71%',
  'Murray St': '65%',
  'N Mex St': '66%',
  'Norfolk St': '71%',
  'N Carolina': '70%',
  'Notre Dame': '61%',
  'Ohio St': '64%',
  'Providence': '61%',
  'Purdue': '48%',
  'Richmond': '61%',
  'Rutgers': '62%',
  'S Dakota St': '64%',
  'San Diego St': '54%',
  'San Fran': '63%',
  'Seton Hall': '70%',
  "St Mary's": '46%',
  "St Peter's": '73%',
  'TAM C. Christi': '74%',
  'TCU': '61%',
  'Tennessee': '45%',
  'Texas': '65%',
  'Texas Tech': '54%',
  'TX Southern': '72%',
  'UAB': '68%',
  'UCLA': '55%',
  'USC': '65%',
  'Vermont': '57%',
  'Villanova': '44%',
  'Virginia Tech': '64%',
  'Wisconsin': '55%',
  'Wright St': '69%',
  'Wyoming': '66%',
  'Yale': '75%',
  'Akron': '80%',
  'Alabama': '51%',
  'Arizona': '45%',
  'Arkansas': '59%'},
 'Baylor': {'Boise St': '59%',
  'Bryant': '67%',
  'Chatt': '65%',
  'Colgate': '68%',
  'Colo St': '54%',
  'Connecticut': '56%',
  'Creighton': '56%',
  'CS Fullerton': '71%',
  'Davidson': '59%',
  'Delaware': '70%',
  'Duke': '56%',
  'Georgia St': '70%',
  'Gonzaga': '55%',
  'Houston': '57%',
  'Illinois': '55%',
  'Indiana': '71%',
  'Iowa': '64%',
  'Iowa St': '60%',
  'Jville St': '69%',
  'Kansas': '43%',
  'Kentucky': '51%',
  'Longwood': '67%',
  'Loyola-Chi': '65%',
  'LSU': '58%',
  'Marquette': '52%',
  'Memphis': '53%',
  'Miami FL': '67%',
  'Michigan': '60%',
  'Michigan St': '51%',
  'Montana St': '66%',
  'Murray St': '63%',
  'N Mex St': '67%',
  'Norfolk St': '72%',
  'N Carolina': '70%',
  'Notre Dame': '69%',
  'Ohio St': '64%',
  'Providence': '59%',
  'Purdue': '48%',
  'Richmond': '64%',
  'Rutgers': '56%',
  'S Dakota St': '58%',
  'San Diego St': '57%',
  'San Fran': '61%',
  'Seton Hall': '65%',
  "St Mary's": '59%',
  "St Peter's": '70%',
  'TAM C. Christi': '72%',
  'TCU': '65%',
  'Tennessee': '49%',
  'Texas': '67%',
  'Texas Tech': '55%',
  'TX Southern': '69%',
  'UAB': '63%',
  'UCLA': '64%',
  'USC': '63%',
  'Vermont': '62%',
  'Villanova': '53%',
  'Virginia Tech': '68%',
  'Wisconsin': '53%',
  'Wright St': '69%',
  'Wyoming': '65%',
  'Yale': '71%',
  'Akron': '80%',
  'Alabama': '52%',
  'Arizona': '54%',
  'Arkansas': '61%',
  'Auburn': '57%'},
 'Boise St': {'Bryant': '68%',
  'Chatt': '65%',
  'Colgate': '68%',
  'Colo St': '54%',
  'Connecticut': '49%',
  'Creighton': '54%',
  'CS Fullerton': '73%',
  'Davidson': '55%',
  'Delaware': '71%',
  'Duke': '48%',
  'Georgia St': '68%',
  'Gonzaga': '38%',
  'Houston': '39%',
  'Illinois': '47%',
  'Indiana': '70%',
  'Iowa': '52%',
  'Iowa St': '62%',
  'Jville St': '66%',
  'Kansas': '39%',
  'Kentucky': '33%',
  'Longwood': '68%',
  'Loyola-Chi': '66%',
  'LSU': '55%',
  'Marquette': '58%',
  'Memphis': '50%',
  'Miami FL': '67%',
  'Michigan': '50%',
  'Michigan St': '46%',
  'Montana St': '63%',
  'Murray St': '56%',
  'N Mex St': '69%',
  'Norfolk St': '69%',
  'N Carolina': '66%',
  'Notre Dame': '77%',
  'Ohio St': '52%',
  'Providence': '56%',
  'Purdue': '45%',
  'Richmond': '65%',
  'Rutgers': '57%',
  'S Dakota St': '57%',
  'San Diego St': '52%',
  'San Fran': '51%',
  'Seton Hall': '60%',
  "St Mary's": '49%',
  "St Peter's": '70%',
  'TAM C. Christi': '73%',
  'TCU': '61%',
  'Tennessee': '43%',
  'Texas': '56%',
  'Texas Tech': '46%',
  'TX Southern': '68%',
  'UAB': '59%',
  'UCLA': '44%',
  'USC': '65%',
  'Vermont': '61%',
  'Villanova': '37%',
  'Virginia Tech': '66%',
  'Wisconsin': '54%',
  'Wright St': '69%',
  'Wyoming': '68%',
  'Yale': '73%',
  'Akron': '78%',
  'Alabama': '48%',
  'Arizona': '46%',
  'Arkansas': '51%',
  'Auburn': '45%',
  'Baylor': '40%'},
 'Bryant': {'Chatt': '33%',
  'Colgate': '39%',
  'Colo St': '29%',
  'Connecticut': '31%',
  'Creighton': '29%',
  'CS Fullerton': '50%',
  'Davidson': '30%',
  'Delaware': '39%',
  'Duke': '21%',
  'Georgia St': '34%',
  'Gonzaga': '22%',
  'Houston': '27%',
  'Illinois': '28%',
  'Indiana': '36%',
  'Iowa': '26%',
  'Iowa St': '31%',
  'Jville St': '34%',
  'Kansas': '24%',
  'Kentucky': '22%',
  'Longwood': '46%',
  'Loyola-Chi': '32%',
  'LSU': '32%',
  'Marquette': '30%',
  'Memphis': '32%',
  'Miami FL': '34%',
  'Michigan': '37%',
  'Michigan St': '31%',
  'Montana St': '44%',
  'Murray St': '27%',
  'N Mex St': '35%',
  'Norfolk St': '50%',
  'N Carolina': '29%',
  'Notre Dame': '33%',
  'Ohio St': '35%',
  'Providence': '35%',
  'Purdue': '32%',
  'Richmond': '32%',
  'Rutgers': '30%',
  'S Dakota St': '35%',
  'San Diego St': '34%',
  'San Fran': '28%',
  'Seton Hall': '32%',
  "St Mary's": '29%',
  "St Peter's": '48%',
  'TAM C. Christi': '53%',
  'TCU': '29%',
  'Tennessee': '22%',
  'Texas': '34%',
  'Texas Tech': '28%',
  'TX Southern': '60%',
  'UAB': '29%',
  'UCLA': '25%',
  'USC': '26%',
  'Vermont': '33%',
  'Villanova': '28%',
  'Virginia Tech': '32%',
  'Wisconsin': '32%',
  'Wright St': '37%',
  'Wyoming': '37%',
  'Yale': '42%',
  'Akron': '48%',
  'Alabama': '35%',
  'Arizona': '28%',
  'Arkansas': '30%',
  'Auburn': '28%',
  'Baylor': '32%',
  'Boise St': '31%'},
 'Chatt': {'Colgate': '57%',
  'Colo St': '36%',
  'Connecticut': '36%',
  'Creighton': '44%',
  'CS Fullerton': '55%',
  'Davidson': '49%',
  'Delaware': '55%',
  'Duke': '34%',
  'Georgia St': '57%',
  'Gonzaga': '31%',
  'Houston': '35%',
  'Illinois': '34%',
  'Indiana': '38%',
  'Iowa': '44%',
  'Iowa St': '37%',
  'Jville St': '55%',
  'Kansas': '32%',
  'Kentucky': '31%',
  'Longwood': '56%',
  'Loyola-Chi': '47%',
  'LSU': '43%',
  'Marquette': '36%',
  'Memphis': '42%',
  'Miami FL': '42%',
  'Michigan': '36%',
  'Michigan St': '40%',
  'Montana St': '56%',
  'Murray St': '47%',
  'N Mex St': '57%',
  'Norfolk St': '59%',
  'N Carolina': '42%',
  'Notre Dame': '45%',
  'Ohio St': '38%',
  'Providence': '42%',
  'Purdue': '37%',
  'Richmond': '51%',
  'Rutgers': '46%',
  'S Dakota St': '48%',
  'San Diego St': '42%',
  'San Fran': '38%',
  'Seton Hall': '36%',
  "St Mary's": '35%',
  "St Peter's": '61%',
  'TAM C. Christi': '65%',
  'TCU': '41%',
  'Tennessee': '31%',
  'Texas': '39%',
  'Texas Tech': '34%',
  'TX Southern': '59%',
  'UAB': '47%',
  'UCLA': '47%',
  'USC': '42%',
  'Vermont': '51%',
  'Villanova': '29%',
  'Virginia Tech': '33%',
  'Wisconsin': '41%',
  'Wright St': '58%',
  'Wyoming': '50%',
  'Yale': '64%',
  'Akron': '68%',
  'Alabama': '44%',
  'Arizona': '35%',
  'Arkansas': '39%',
  'Auburn': '32%',
  'Baylor': '34%',
  'Boise St': '34%',
  'Bryant': '66%'},
 'Colgate': {'Colo St': '27%',
  'Connecticut': '28%',
  'Creighton': '33%',
  'CS Fullerton': '50%',
  'Davidson': '31%',
  'Delaware': '53%',
  'Duke': '25%',
  'Georgia St': '53%',
  'Gonzaga': '21%',
  'Houston': '33%',
  'Illinois': '30%',
  'Indiana': '42%',
  'Iowa': '28%',
  'Iowa St': '36%',
  'Jville St': '51%',
  'Kansas': '22%',
  'Kentucky': '24%',
  'Longwood': '62%',
  'Loyola-Chi': '37%',
  'LSU': '38%',
  'Marquette': '33%',
  'Memphis': '36%',
  'Miami FL': '41%',
  'Michigan': '36%',
  'Michigan St': '33%',
  'Montana St': '53%',
  'Murray St': '31%',
  'N Mex St': '39%',
  'Norfolk St': '57%',
  'N Carolina': '37%',
  'Notre Dame': '37%',
  'Ohio St': '34%',
  'Providence': '30%',
  'Purdue': '28%',
  'Richmond': '34%',
  'Rutgers': '28%',
  'S Dakota St': '38%',
  'San Diego St': '33%',
  'San Fran': '28%',
  'Seton Hall': '36%',
  "St Mary's": '31%',
  "St Peter's": '51%',
  'TAM C. Christi': '60%',
  'TCU': '36%',
  'Tennessee': '23%',
  'Texas': '38%',
  'Texas Tech': '27%',
  'TX Southern': '54%',
  'UAB': '34%',
  'UCLA': '26%',
  'USC': '32%',
  'Vermont': '34%',
  'Villanova': '25%',
  'Virginia Tech': '35%',
  'Wisconsin': '33%',
  'Wright St': '48%',
  'Wyoming': '35%',
  'Yale': '59%',
  'Akron': '50%',
  'Alabama': '42%',
  'Arizona': '28%',
  'Arkansas': '32%',
  'Auburn': '30%',
  'Baylor': '31%',
  'Boise St': '31%',
  'Bryant': '60%',
  'Chatt': '42%'},
 'Colo St': {'Connecticut': '46%',
  'Creighton': '54%',
  'CS Fullerton': '66%',
  'Davidson': '58%',
  'Delaware': '66%',
  'Duke': '38%',
  'Georgia St': '67%',
  'Gonzaga': '30%',
  'Houston': '35%',
  'Illinois': '47%',
  'Indiana': '64%',
  'Iowa': '44%',
  'Iowa St': '58%',
  'Jville St': '69%',
  'Kansas': '35%',
  'Kentucky': '32%',
  'Longwood': '68%',
  'Loyola-Chi': '63%',
  'LSU': '51%',
  'Marquette': '60%',
  'Memphis': '52%',
  'Miami FL': '69%',
  'Michigan': '52%',
  'Michigan St': '55%',
  'Montana St': '64%',
  'Murray St': '54%',
  'N Mex St': '65%',
  'Norfolk St': '69%',
  'N Carolina': '63%',
  'Notre Dame': '73%',
  'Ohio St': '49%',
  'Providence': '58%',
  'Purdue': '43%',
  'Richmond': '58%',
  'Rutgers': '60%',
  'S Dakota St': '55%',
  'San Diego St': '42%',
  'San Fran': '51%',
  'Seton Hall': '59%',
  "St Mary's": '41%',
  "St Peter's": '60%',
  'TAM C. Christi': '69%',
  'TCU': '61%',
  'Tennessee': '38%',
  'Texas': '46%',
  'Texas Tech': '43%',
  'TX Southern': '62%',
  'UAB': '56%',
  'UCLA': '45%',
  'USC': '63%',
  'Vermont': '62%',
  'Villanova': '38%',
  'Virginia Tech': '55%',
  'Wisconsin': '42%',
  'Wright St': '68%',
  'Wyoming': '65%',
  'Yale': '72%',
  'Akron': '77%',
  'Alabama': '50%',
  'Arizona': '44%',
  'Arkansas': '44%',
  'Auburn': '45%',
  'Baylor': '45%',
  'Boise St': '45%',
  'Bryant': '70%',
  'Chatt': '63%',
  'Colgate': '72%'},
 'Connecticut': {'Creighton': '49%',
  'CS Fullerton': '66%',
  'Davidson': '53%',
  'Delaware': '68%',
  'Duke': '49%',
  'Georgia St': '67%',
  'Gonzaga': '40%',
  'Houston': '47%',
  'Illinois': '49%',
  'Indiana': '67%',
  'Iowa': '57%',
  'Iowa St': '57%',
  'Jville St': '65%',
  'Kansas': '36%',
  'Kentucky': '37%',
  'Longwood': '63%',
  'Loyola-Chi': '58%',
  'LSU': '47%',
  'Marquette': '51%',
  'Memphis': '51%',
  'Miami FL': '58%',
  'Michigan': '57%',
  'Michigan St': '46%',
  'Montana St': '65%',
  'Murray St': '57%',
  'N Mex St': '68%',
  'Norfolk St': '68%',
  'N Carolina': '62%',
  'Notre Dame': '60%',
  'Ohio St': '60%',
  'Providence': '58%',
  'Purdue': '36%',
  'Richmond': '55%',
  'Rutgers': '50%',
  'S Dakota St': '51%',
  'San Diego St': '50%',
  'San Fran': '57%',
  'Seton Hall': '64%',
  "St Mary's": '46%',
  "St Peter's": '66%',
  'TAM C. Christi': '71%',
  'TCU': '54%',
  'Tennessee': '38%',
  'Texas': '61%',
  'Texas Tech': '48%',
  'TX Southern': '69%',
  'UAB': '57%',
  'UCLA': '50%',
  'USC': '58%',
  'Vermont': '55%',
  'Villanova': '40%',
  'Virginia Tech': '54%',
  'Wisconsin': '56%',
  'Wright St': '66%',
  'Wyoming': '61%',
  'Yale': '70%',
  'Akron': '76%',
  'Alabama': '50%',
  'Arizona': '42%',
  'Arkansas': '55%',
  'Auburn': '42%',
  'Baylor': '43%',
  'Boise St': '50%',
  'Bryant': '68%',
  'Chatt': '63%',
  'Colgate': '71%',
  'Colo St': '53%'},
 'Creighton': {'CS Fullerton': '63%',
  'Davidson': '57%',
  'Delaware': '63%',
  'Duke': '40%',
  'Georgia St': '62%',
  'Gonzaga': '30%',
  'Houston': '46%',
  'Illinois': '44%',
  'Indiana': '57%',
  'Iowa': '44%',
  'Iowa St': '53%',
  'Jville St': '62%',
  'Kansas': '30%',
  'Kentucky': '29%',
  'Longwood': '62%',
  'Loyola-Chi': '53%',
  'LSU': '50%',
  'Marquette': '47%',
  'Memphis': '53%',
  'Miami FL': '59%',
  'Michigan': '45%',
  'Michigan St': '45%',
  'Montana St': '56%',
  'Murray St': '50%',
  'N Mex St': '65%',
  'Norfolk St': '64%',
  'N Carolina': '55%',
  'Notre Dame': '63%',
  'Ohio St': '49%',
  'Providence': '46%',
  'Purdue': '42%',
  'Richmond': '55%',
  'Rutgers': '54%',
  'S Dakota St': '55%',
  'San Diego St': '46%',
  'San Fran': '51%',
  'Seton Hall': '50%',
  "St Mary's": '40%',
  "St Peter's": '62%',
  'TAM C. Christi': '64%',
  'TCU': '52%',
  'Tennessee': '33%',
  'Texas': '44%',
  'Texas Tech': '43%',
  'TX Southern': '64%',
  'UAB': '48%',
  'UCLA': '49%',
  'USC': '47%',
  'Vermont': '50%',
  'Villanova': '31%',
  'Virginia Tech': '47%',
  'Wisconsin': '47%',
  'Wright St': '63%',
  'Wyoming': '61%',
  'Yale': '65%',
  'Akron': '68%',
  'Alabama': '46%',
  'Arizona': '45%',
  'Arkansas': '48%',
  'Auburn': '47%',
  'Baylor': '43%',
  'Boise St': '45%',
  'Bryant': '70%',
  'Chatt': '55%',
  'Colgate': '66%',
  'Colo St': '45%',
  'Connecticut': '50%'},
 'CS Fullerton': {'Davidson': '24%',
  'Delaware': '38%',
  'Duke': '19%',
  'Georgia St': '34%',
  'Gonzaga': '19%',
  'Houston': '25%',
  'Illinois': '25%',
  'Indiana': '32%',
  'Iowa': '22%',
  'Iowa St': '27%',
  'Jville St': '42%',
  'Kansas': '16%',
  'Kentucky': '17%',
  'Longwood': '46%',
  'Loyola-Chi': '27%',
  'LSU': '30%',
  'Marquette': '27%',
  'Memphis': '27%',
  'Miami FL': '26%',
  'Michigan': '29%',
  'Michigan St': '25%',
  'Montana St': '50%',
  'Murray St': '23%',
  'N Mex St': '33%',
  'Norfolk St': '46%',
  'N Carolina': '30%',
  'Notre Dame': '31%',
  'Ohio St': '30%',
  'Providence': '25%',
  'Purdue': '24%',
  'Richmond': '26%',
  'Rutgers': '25%',
  'S Dakota St': '29%',
  'San Diego St': '25%',
  'San Fran': '21%',
  'Seton Hall': '28%',
  "St Mary's": '23%',
  "St Peter's": '45%',
  'TAM C. Christi': '56%',
  'TCU': '29%',
  'Tennessee': '17%',
  'Texas': '29%',
  'Texas Tech': '22%',
  'TX Southern': '54%',
  'UAB': '21%',
  'UCLA': '20%',
  'USC': '27%',
  'Vermont': '37%',
  'Villanova': '20%',
  'Virginia Tech': '32%',
  'Wisconsin': '21%',
  'Wright St': '54%',
  'Wyoming': '27%',
  'Yale': '39%',
  'Akron': '47%',
  'Alabama': '39%',
  'Arizona': '30%',
  'Arkansas': '30%',
  'Auburn': '29%',
  'Baylor': '28%',
  'Boise St': '26%',
  'Bryant': '49%',
  'Chatt': '44%',
  'Colgate': '49%',
  'Colo St': '33%',
  'Connecticut': '33%',
  'Creighton': '36%'},
 'Davidson': {'Delaware': '67%',
  'Duke': '31%',
  'Georgia St': '65%',
  'Gonzaga': '26%',
  'Houston': '37%',
  'Illinois': '39%',
  'Indiana': '51%',
  'Iowa': '38%',
  'Iowa St': '44%',
  'Jville St': '66%',
  'Kansas': '35%',
  'Kentucky': '33%',
  'Longwood': '63%',
  'Loyola-Chi': '50%',
  'LSU': '44%',
  'Marquette': '48%',
  'Memphis': '49%',
  'Miami FL': '50%',
  'Michigan': '44%',
  'Michigan St': '48%',
  'Montana St': '62%',
  'Murray St': '57%',
  'N Mex St': '61%',
  'Norfolk St': '66%',
  'N Carolina': '48%',
  'Notre Dame': '57%',
  'Ohio St': '40%',
  'Providence': '46%',
  'Purdue': '38%',
  'Richmond': '48%',
  'Rutgers': '48%',
  'S Dakota St': '52%',
  'San Diego St': '44%',
  'San Fran': '49%',
  'Seton Hall': '43%',
  "St Mary's": '38%',
  "St Peter's": '58%',
  'TAM C. Christi': '65%',
  'TCU': '47%',
  'Tennessee': '36%',
  'Texas': '37%',
  'Texas Tech': '38%',
  'TX Southern': '63%',
  'UAB': '61%',
  'UCLA': '38%',
  'USC': '46%',
  'Vermont': '57%',
  'Villanova': '26%',
  'Virginia Tech': '40%',
  'Wisconsin': '38%',
  'Wright St': '64%',
  'Wyoming': '56%',
  'Yale': '62%',
  'Akron': '77%',
  'Alabama': '49%',
  'Arizona': '36%',
  'Arkansas': '42%',
  'Auburn': '36%',
  'Baylor': '40%',
  'Boise St': '44%',
  'Bryant': '69%',
  'Chatt': '50%',
  'Colgate': '68%',
  'Colo St': '41%',
  'Connecticut': '46%',
  'Creighton': '42%',
  'CS Fullerton': '75%'},
 'Delaware': {'Duke': '20%',
  'Georgia St': '58%',
  'Gonzaga': '19%',
  'Houston': '27%',
  'Illinois': '25%',
  'Indiana': '35%',
  'Iowa': '25%',
  'Iowa St': '30%',
  'Jville St': '55%',
  'Kansas': '19%',
  'Kentucky': '18%',
  'Longwood': '52%',
  'Loyola-Chi': '32%',
  'LSU': '33%',
  'Marquette': '29%',
  'Memphis': '31%',
  'Miami FL': '31%',
  'Michigan': '31%',
  'Michigan St': '27%',
  'Montana St': '52%',
  'Murray St': '36%',
  'N Mex St': '40%',
  'Norfolk St': '61%',
  'N Carolina': '29%',
  'Notre Dame': '30%',
  'Ohio St': '31%',
  'Providence': '26%',
  'Purdue': '22%',
  'Richmond': '28%',
  'Rutgers': '26%',
  'S Dakota St': '40%',
  'San Diego St': '29%',
  'San Fran': '27%',
  'Seton Hall': '30%',
  "St Mary's": '25%',
  "St Peter's": '50%',
  'TAM C. Christi': '62%',
  'TCU': '32%',
  'Tennessee': '21%',
  'Texas': '31%',
  'Texas Tech': '25%',
  'TX Southern': '53%',
  'UAB': '28%',
  'UCLA': '24%',
  'USC': '30%',
  'Vermont': '38%',
  'Villanova': '22%',
  'Virginia Tech': '31%',
  'Wisconsin': '27%',
  'Wright St': '56%',
  'Wyoming': '36%',
  'Yale': '57%',
  'Akron': '56%',
  'Alabama': '37%',
  'Arizona': '27%',
  'Arkansas': '31%',
  'Auburn': '30%',
  'Baylor': '29%',
  'Boise St': '28%',
  'Bryant': '60%',
  'Chatt': '44%',
  'Colgate': '46%',
  'Colo St': '33%',
  'Connecticut': '31%',
  'Creighton': '36%',
  'CS Fullerton': '61%',
  'Davidson': '32%'},
 'Duke': {'Georgia St': '66%',
  'Gonzaga': '47%',
  'Houston': '48%',
  'Illinois': '49%',
  'Indiana': '57%',
  'Iowa': '58%',
  'Iowa St': '58%',
  'Jville St': '70%',
  'Kansas': '45%',
  'Kentucky': '47%',
  'Longwood': '66%',
  'Loyola-Chi': '67%',
  'LSU': '54%',
  'Marquette': '54%',
  'Memphis': '54%',
  'Miami FL': '58%',
  'Michigan': '57%',
  'Michigan St': '48%',
  'Montana St': '65%',
  'Murray St': '60%',
  'N Mex St': '62%',
  'Norfolk St': '70%',
  'N Carolina': '60%',
  'Notre Dame': '65%',
  'Ohio St': '59%',
  'Providence': '61%',
  'Purdue': '48%',
  'Richmond': '56%',
  'Rutgers': '52%',
  'S Dakota St': '61%',
  'San Diego St': '57%',
  'San Fran': '51%',
  'Seton Hall': '56%',
  "St Mary's": '53%',
  "St Peter's": '65%',
  'TAM C. Christi': '67%',
  'TCU': '51%',
  'Tennessee': '48%',
  'Texas': '56%',
  'Texas Tech': '50%',
  'TX Southern': '64%',
  'UAB': '59%',
  'UCLA': '55%',
  'USC': '58%',
  'Vermont': '66%',
  'Villanova': '50%',
  'Virginia Tech': '63%',
  'Wisconsin': '52%',
  'Wright St': '70%',
  'Wyoming': '58%',
  'Yale': '71%',
  'Akron': '77%',
  'Alabama': '49%',
  'Arizona': '51%',
  'Arkansas': '62%',
  'Auburn': '44%',
  'Baylor': '43%',
  'Boise St': '51%',
  'Bryant': '78%',
  'Chatt': '65%',
  'Colgate': '74%',
  'Colo St': '61%',
  'Connecticut': '50%',
  'Creighton': '59%',
  'CS Fullerton': '80%',
  'Davidson': '68%',
  'Delaware': '79%'},
 'Georgia St': {'Gonzaga': '23%',
  'Houston': '25%',
  'Illinois': '29%',
  'Indiana': '34%',
  'Iowa': '22%',
  'Iowa St': '25%',
  'Jville St': '42%',
  'Kansas': '23%',
  'Kentucky': '21%',
  'Longwood': '47%',
  'Loyola-Chi': '31%',
  'LSU': '27%',
  'Marquette': '22%',
  'Memphis': '31%',
  'Miami FL': '24%',
  'Michigan': '33%',
  'Michigan St': '30%',
  'Montana St': '48%',
  'Murray St': '26%',
  'N Mex St': '37%',
  'Norfolk St': '54%',
  'N Carolina': '28%',
  'Notre Dame': '30%',
  'Ohio St': '33%',
  'Providence': '30%',
  'Purdue': '30%',
  'Richmond': '21%',
  'Rutgers': '28%',
  'S Dakota St': '37%',
  'San Diego St': '25%',
  'San Fran': '25%',
  'Seton Hall': '25%',
  "St Mary's": '22%',
  "St Peter's": '44%',
  'TAM C. Christi': '53%',
  'TCU': '28%',
  'Tennessee': '20%',
  'Texas': '30%',
  'Texas Tech': '27%',
  'TX Southern': '55%',
  'UAB': '23%',
  'UCLA': '21%',
  'USC': '28%',
  'Vermont': '37%',
  'Villanova': '26%',
  'Virginia Tech': '27%',
  'Wisconsin': '28%',
  'Wright St': '45%',
  'Wyoming': '31%',
  'Yale': '42%',
  'Akron': '48%',
  'Alabama': '37%',
  'Arizona': '29%',
  'Arkansas': '32%',
  'Auburn': '29%',
  'Baylor': '29%',
  'Boise St': '31%',
  'Bryant': '65%',
  'Chatt': '42%',
  'Colgate': '46%',
  'Colo St': '32%',
  'Connecticut': '32%',
  'Creighton': '37%',
  'CS Fullerton': '65%',
  'Davidson': '34%',
  'Delaware': '41%',
  'Duke': '33%'},
 'Gonzaga': {'Houston': '45%',
  'Illinois': '61%',
  'Indiana': '71%',
  'Iowa': '64%',
  'Iowa St': '65%',
  'Jville St': '71%',
  'Kansas': '54%',
  'Kentucky': '54%',
  'Longwood': '67%',
  'Loyola-Chi': '66%',
  'LSU': '57%',
  'Marquette': '62%',
  'Memphis': '61%',
  'Miami FL': '67%',
  'Michigan': '64%',
  'Michigan St': '62%',
  'Montana St': '65%',
  'Murray St': '61%',
  'N Mex St': '65%',
  'Norfolk St': '69%',
  'N Carolina': '67%',
  'Notre Dame': '72%',
  'Ohio St': '68%',
  'Providence': '62%',
  'Purdue': '57%',
  'Richmond': '64%',
  'Rutgers': '71%',
  'S Dakota St': '62%',
  'San Diego St': '55%',
  'San Fran': '58%',
  'Seton Hall': '67%',
  "St Mary's": '56%',
  "St Peter's": '60%',
  'TAM C. Christi': '68%',
  'TCU': '64%',
  'Tennessee': '56%',
  'Texas': '57%',
  'Texas Tech': '54%',
  'TX Southern': '65%',
  'UAB': '62%',
  'UCLA': '59%',
  'USC': '65%',
  'Vermont': '61%',
  'Villanova': '61%',
  'Virginia Tech': '65%',
  'Wisconsin': '58%',
  'Wright St': '68%',
  'Wyoming': '65%',
  'Yale': '72%',
  'Akron': '80%',
  'Alabama': '62%',
  'Arizona': '54%',
  'Arkansas': '65%',
  'Auburn': '53%',
  'Baylor': '44%',
  'Boise St': '61%',
  'Bryant': '77%',
  'Chatt': '68%',
  'Colgate': '78%',
  'Colo St': '69%',
  'Connecticut': '59%',
  'Creighton': '69%',
  'CS Fullerton': '80%',
  'Davidson': '73%',
  'Delaware': '80%',
  'Duke': '52%',
  'Georgia St': '76%'},
 'Houston': {'Illinois': '53%',
  'Indiana': '61%',
  'Iowa': '57%',
  'Iowa St': '59%',
  'Jville St': '65%',
  'Kansas': '47%',
  'Kentucky': '39%',
  'Longwood': '64%',
  'Loyola-Chi': '64%',
  'LSU': '55%',
  'Marquette': '52%',
  'Memphis': '54%',
  'Miami FL': '56%',
  'Michigan': '57%',
  'Michigan St': '53%',
  'Montana St': '67%',
  'Murray St': '59%',
  'N Mex St': '60%',
  'Norfolk St': '65%',
  'N Carolina': '63%',
  'Notre Dame': '61%',
  'Ohio St': '59%',
  'Providence': '54%',
  'Purdue': '50%',
  'Richmond': '54%',
  'Rutgers': '55%',
  'S Dakota St': '58%',
  'San Diego St': '54%',
  'San Fran': '52%',
  'Seton Hall': '62%',
  "St Mary's": '51%',
  "St Peter's": '64%',
  'TAM C. Christi': '68%',
  'TCU': '54%',
  'Tennessee': '50%',
  'Texas': '59%',
  'Texas Tech': '58%',
  'TX Southern': '63%',
  'UAB': '56%',
  'UCLA': '53%',
  'USC': '62%',
  'Vermont': '59%',
  'Villanova': '49%',
  'Virginia Tech': '58%',
  'Wisconsin': '53%',
  'Wright St': '65%',
  'Wyoming': '61%',
  'Yale': '64%',
  'Akron': '76%',
  'Alabama': '50%',
  'Arizona': '51%',
  'Arkansas': '58%',
  'Auburn': '46%',
  'Baylor': '42%',
  'Boise St': '60%',
  'Bryant': '72%',
  'Chatt': '64%',
  'Colgate': '66%',
  'Colo St': '64%',
  'Connecticut': '52%',
  'Creighton': '53%',
  'CS Fullerton': '74%',
  'Davidson': '62%',
  'Delaware': '72%',
  'Duke': '51%',
  'Georgia St': '74%',
  'Gonzaga': '54%'},
 'Illinois': {'Indiana': '65%',
  'Iowa': '51%',
  'Iowa St': '60%',
  'Jville St': '62%',
  'Kansas': '39%',
  'Kentucky': '34%',
  'Longwood': '63%',
  'Loyola-Chi': '56%',
  'LSU': '48%',
  'Marquette': '53%',
  'Memphis': '54%',
  'Miami FL': '57%',
  'Michigan': '63%',
  'Michigan St': '43%',
  'Montana St': '59%',
  'Murray St': '57%',
  'N Mex St': '67%',
  'Norfolk St': '64%',
  'N Carolina': '61%',
  'Notre Dame': '58%',
  'Ohio St': '64%',
  'Providence': '60%',
  'Purdue': '39%',
  'Richmond': '59%',
  'Rutgers': '49%',
  'S Dakota St': '52%',
  'San Diego St': '45%',
  'San Fran': '58%',
  'Seton Hall': '68%',
  "St Mary's": '45%',
  "St Peter's": '62%',
  'TAM C. Christi': '64%',
  'TCU': '64%',
  'Tennessee': '36%',
  'Texas': '55%',
  'Texas Tech': '41%',
  'TX Southern': '63%',
  'UAB': '51%',
  'UCLA': '41%',
  'USC': '56%',
  'Vermont': '53%',
  'Villanova': '35%',
  'Virginia Tech': '52%',
  'Wisconsin': '55%',
  'Wright St': '64%',
  'Wyoming': '65%',
  'Yale': '68%',
  'Akron': '77%',
  'Alabama': '53%',
  'Arizona': '43%',
  'Arkansas': '56%',
  'Auburn': '43%',
  'Baylor': '44%',
  'Boise St': '52%',
  'Bryant': '71%',
  'Chatt': '65%',
  'Colgate': '69%',
  'Colo St': '52%',
  'Connecticut': '50%',
  'Creighton': '55%',
  'CS Fullerton': '74%',
  'Davidson': '60%',
  'Delaware': '74%',
  'Duke': '50%',
  'Georgia St': '70%',
  'Gonzaga': '38%',
  'Houston': '46%'},
 'Indiana': {'Iowa': '33%',
  'Iowa St': '42%',
  'Jville St': '62%',
  'Kansas': '23%',
  'Kentucky': '20%',
  'Longwood': '62%',
  'Loyola-Chi': '53%',
  'LSU': '42%',
  'Marquette': '38%',
  'Memphis': '42%',
  'Miami FL': '53%',
  'Michigan': '45%',
  'Michigan St': '39%',
  'Montana St': '64%',
  'Murray St': '48%',
  'N Mex St': '62%',
  'Norfolk St': '64%',
  'N Carolina': '38%',
  'Notre Dame': '56%',
  'Ohio St': '39%',
  'Providence': '39%',
  'Purdue': '25%',
  'Richmond': '45%',
  'Rutgers': '48%',
  'S Dakota St': '53%',
  'San Diego St': '28%',
  'San Fran': '37%',
  'Seton Hall': '50%',
  "St Mary's": '28%',
  "St Peter's": '61%',
  'TAM C. Christi': '67%',
  'TCU': '45%',
  'Tennessee': '22%',
  'Texas': '38%',
  'Texas Tech': '32%',
  'TX Southern': '62%',
  'UAB': '53%',
  'UCLA': '28%',
  'USC': '46%',
  'Vermont': '56%',
  'Villanova': '23%',
  'Virginia Tech': '45%',
  'Wisconsin': '31%',
  'Wright St': '61%',
  'Wyoming': '59%',
  'Yale': '66%',
  'Akron': '64%',
  'Alabama': '39%',
  'Arizona': '32%',
  'Arkansas': '31%',
  'Auburn': '25%',
  'Baylor': '28%',
  'Boise St': '29%',
  'Bryant': '63%',
  'Chatt': '61%',
  'Colgate': '57%',
  'Colo St': '35%',
  'Connecticut': '32%',
  'Creighton': '42%',
  'CS Fullerton': '67%',
  'Davidson': '48%',
  'Delaware': '64%',
  'Duke': '42%',
  'Georgia St': '65%',
  'Gonzaga': '28%',
  'Houston': '38%',
  'Illinois': '34%'},
 'Iowa': {'Iowa St': '51%',
  'Jville St': '68%',
  'Kansas': '39%',
  'Kentucky': '39%',
  'Longwood': '67%',
  'Loyola-Chi': '61%',
  'LSU': '49%',
  'Marquette': '50%',
  'Memphis': '51%',
  'Miami FL': '52%',
  'Michigan': '56%',
  'Michigan St': '52%',
  'Montana St': '67%',
  'Murray St': '63%',
  'N Mex St': '69%',
  'Norfolk St': '67%',
  'N Carolina': '57%',
  'Notre Dame': '57%',
  'Ohio St': '58%',
  'Providence': '60%',
  'Purdue': '48%',
  'Richmond': '57%',
  'Rutgers': '55%',
  'S Dakota St': '63%',
  'San Diego St': '54%',
  'San Fran': '55%',
  'Seton Hall': '56%',
  "St Mary's": '52%',
  "St Peter's": '65%',
  'TAM C. Christi': '66%',
  'TCU': '48%',
  'Tennessee': '37%',
  'Texas': '55%',
  'Texas Tech': '47%',
  'TX Southern': '68%',
  'UAB': '56%',
  'UCLA': '45%',
  'USC': '58%',
  'Vermont': '59%',
  'Villanova': '42%',
  'Virginia Tech': '58%',
  'Wisconsin': '59%',
  'Wright St': '67%',
  'Wyoming': '60%',
  'Yale': '72%',
  'Akron': '74%',
  'Alabama': '47%',
  'Arizona': '32%',
  'Arkansas': '46%',
  'Auburn': '31%',
  'Baylor': '35%',
  'Boise St': '47%',
  'Bryant': '73%',
  'Chatt': '55%',
  'Colgate': '71%',
  'Colo St': '55%',
  'Connecticut': '42%',
  'Creighton': '55%',
  'CS Fullerton': '77%',
  'Davidson': '61%',
  'Delaware': '74%',
  'Duke': '41%',
  'Georgia St': '77%',
  'Gonzaga': '35%',
  'Houston': '42%',
  'Illinois': '48%',
  'Indiana': '66%'},
 'Iowa St': {'Jville St': '61%',
  'Kansas': '25%',
  'Kentucky': '25%',
  'Longwood': '60%',
  'Loyola-Chi': '54%',
  'LSU': '41%',
  'Marquette': '45%',
  'Memphis': '44%',
  'Miami FL': '56%',
  'Michigan': '48%',
  'Michigan St': '41%',
  'Montana St': '59%',
  'Murray St': '50%',
  'N Mex St': '62%',
  'Norfolk St': '61%',
  'N Carolina': '43%',
  'Notre Dame': '62%',
  'Ohio St': '46%',
  'Providence': '43%',
  'Purdue': '32%',
  'Richmond': '45%',
  'Rutgers': '56%',
  'S Dakota St': '55%',
  'San Diego St': '34%',
  'San Fran': '42%',
  'Seton Hall': '52%',
  "St Mary's": '25%',
  "St Peter's": '65%',
  'TAM C. Christi': '64%',
  'TCU': '45%',
  'Tennessee': '26%',
  'Texas': '46%',
  'Texas Tech': '31%',
  'TX Southern': '67%',
  'UAB': '49%',
  'UCLA': '35%',
  'USC': '50%',
  'Vermont': '54%',
  'Villanova': '27%',
  'Virginia Tech': '37%',
  'Wisconsin': '35%',
  'Wright St': '61%',
  'Wyoming': '54%',
  'Yale': '66%',
  'Akron': '69%',
  'Alabama': '46%',
  'Arizona': '40%',
  'Arkansas': '41%',
  'Auburn': '30%',
  'Baylor': '39%',
  'Boise St': '37%',
  'Bryant': '68%',
  'Chatt': '62%',
  'Colgate': '63%',
  'Colo St': '41%',
  'Connecticut': '42%',
  'Creighton': '46%',
  'CS Fullerton': '72%',
  'Davidson': '55%',
  'Delaware': '69%',
  'Duke': '41%',
  'Georgia St': '74%',
  'Gonzaga': '34%',
  'Houston': '40%',
  'Illinois': '39%',
  'Indiana': '57%',
  'Iowa': '48%'},
 'Jville St': {'Kansas': '18%',
  'Kentucky': '19%',
  'Longwood': '53%',
  'Loyola-Chi': '31%',
  'LSU': '37%',
  'Marquette': '28%',
  'Memphis': '33%',
  'Miami FL': '29%',
  'Michigan': '31%',
  'Michigan St': '26%',
  'Montana St': '49%',
  'Murray St': '29%',
  'N Mex St': '32%',
  'Norfolk St': '59%',
  'N Carolina': '28%',
  'Notre Dame': '33%',
  'Ohio St': '34%',
  'Providence': '27%',
  'Purdue': '23%',
  'Richmond': '28%',
  'Rutgers': '25%',
  'S Dakota St': '32%',
  'San Diego St': '28%',
  'San Fran': '27%',
  'Seton Hall': '29%',
  "St Mary's": '23%',
  "St Peter's": '51%',
  'TAM C. Christi': '55%',
  'TCU': '30%',
  'Tennessee': '21%',
  'Texas': '37%',
  'Texas Tech': '27%',
  'TX Southern': '53%',
  'UAB': '25%',
  'UCLA': '24%',
  'USC': '30%',
  'Vermont': '36%',
  'Villanova': '23%',
  'Virginia Tech': '30%',
  'Wisconsin': '27%',
  'Wright St': '43%',
  'Wyoming': '33%',
  'Yale': '54%',
  'Akron': '45%',
  'Alabama': '41%',
  'Arizona': '29%',
  'Arkansas': '32%',
  'Auburn': '30%',
  'Baylor': '30%',
  'Boise St': '33%',
  'Bryant': '65%',
  'Chatt': '44%',
  'Colgate': '48%',
  'Colo St': '30%',
  'Connecticut': '34%',
  'Creighton': '37%',
  'CS Fullerton': '57%',
  'Davidson': '33%',
  'Delaware': '44%',
  'Duke': '29%',
  'Georgia St': '57%',
  'Gonzaga': '28%',
  'Houston': '34%',
  'Illinois': '37%',
  'Indiana': '37%',
  'Iowa': '31%',
  'Iowa St': '38%'},
 'Kansas': {'Kentucky': '51%',
  'Longwood': '66%',
  'Loyola-Chi': '67%',
  'LSU': '62%',
  'Marquette': '62%',
  'Memphis': '65%',
  'Miami FL': '70%',
  'Michigan': '66%',
  'Michigan St': '54%',
  'Montana St': '68%',
  'Murray St': '64%',
  'N Mex St': '65%',
  'Norfolk St': '68%',
  'N Carolina': '72%',
  'Notre Dame': '69%',
  'Ohio St': '63%',
  'Providence': '59%',
  'Purdue': '53%',
  'Richmond': '65%',
  'Rutgers': '54%',
  'S Dakota St': '63%',
  'San Diego St': '65%',
  'San Fran': '70%',
  'Seton Hall': '69%',
  "St Mary's": '50%',
  "St Peter's": '68%',
  'TAM C. Christi': '71%',
  'TCU': '69%',
  'Tennessee': '48%',
  'Texas': '64%',
  'Texas Tech': '59%',
  'TX Southern': '67%',
  'UAB': '63%',
  'UCLA': '62%',
  'USC': '66%',
  'Vermont': '61%',
  'Villanova': '47%',
  'Virginia Tech': '67%',
  'Wisconsin': '61%',
  'Wright St': '72%',
  'Wyoming': '67%',
  'Yale': '73%',
  'Akron': '83%',
  'Alabama': '60%',
  'Arizona': '43%',
  'Arkansas': '67%',
  'Auburn': '53%',
  'Baylor': '56%',
  'Boise St': '60%',
  'Bryant': '75%',
  'Chatt': '67%',
  'Colgate': '77%',
  'Colo St': '64%',
  'Connecticut': '63%',
  'Creighton': '69%',
  'CS Fullerton': '83%',
  'Davidson': '64%',
  'Delaware': '80%',
  'Duke': '54%',
  'Georgia St': '76%',
  'Gonzaga': '45%',
  'Houston': '52%',
  'Illinois': '60%',
  'Indiana': '76%',
  'Iowa': '60%',
  'Iowa St': '74%',
  'Jville St': '81%'},
 'Kentucky': {'Longwood': '70%',
  'Loyola-Chi': '69%',
  'LSU': '62%',
  'Marquette': '61%',
  'Memphis': '65%',
  'Miami FL': '68%',
  'Michigan': '63%',
  'Michigan St': '55%',
  'Montana St': '69%',
  'Murray St': '62%',
  'N Mex St': '64%',
  'Norfolk St': '71%',
  'N Carolina': '73%',
  'Notre Dame': '72%',
  'Ohio St': '67%',
  'Providence': '56%',
  'Purdue': '56%',
  'Richmond': '63%',
  'Rutgers': '58%',
  'S Dakota St': '64%',
  'San Diego St': '55%',
  'San Fran': '61%',
  'Seton Hall': '64%',
  "St Mary's": '62%',
  "St Peter's": '69%',
  'TAM C. Christi': '70%',
  'TCU': '68%',
  'Tennessee': '51%',
  'Texas': '67%',
  'Texas Tech': '57%',
  'TX Southern': '70%',
  'UAB': '65%',
  'UCLA': '60%',
  'USC': '64%',
  'Vermont': '66%',
  'Villanova': '55%',
  'Virginia Tech': '67%',
  'Wisconsin': '56%',
  'Wright St': '71%',
  'Wyoming': '67%',
  'Yale': '72%',
  'Akron': '80%',
  'Alabama': '56%',
  'Arizona': '51%',
  'Arkansas': '67%',
  'Auburn': '53%',
  'Baylor': '48%',
  'Boise St': '66%',
  'Bryant': '77%',
  'Chatt': '68%',
  'Colgate': '75%',
  'Colo St': '67%',
  'Connecticut': '62%',
  'Creighton': '70%',
  'CS Fullerton': '82%',
  'Davidson': '66%',
  'Delaware': '81%',
  'Duke': '52%',
  'Georgia St': '78%',
  'Gonzaga': '45%',
  'Houston': '60%',
  'Illinois': '65%',
  'Indiana': '79%',
  'Iowa': '60%',
  'Iowa St': '74%',
  'Jville St': '80%',
  'Kansas': '48%'},
 'Longwood': {'Loyola-Chi': '28%',
  'LSU': '31%',
  'Marquette': '36%',
  'Memphis': '30%',
  'Miami FL': '34%',
  'Michigan': '33%',
  'Michigan St': '31%',
  'Montana St': '47%',
  'Murray St': '24%',
  'N Mex St': '35%',
  'Norfolk St': '58%',
  'N Carolina': '34%',
  'Notre Dame': '32%',
  'Ohio St': '33%',
  'Providence': '31%',
  'Purdue': '25%',
  'Richmond': '35%',
  'Rutgers': '33%',
  'S Dakota St': '30%',
  'San Diego St': '31%',
  'San Fran': '25%',
  'Seton Hall': '32%',
  "St Mary's": '28%',
  "St Peter's": '55%',
  'TAM C. Christi': '60%',
  'TCU': '35%',
  'Tennessee': '18%',
  'Texas': '32%',
  'Texas Tech': '22%',
  'TX Southern': '52%',
  'UAB': '24%',
  'UCLA': '23%',
  'USC': '30%',
  'Vermont': '36%',
  'Villanova': '24%',
  'Virginia Tech': '36%',
  'Wisconsin': '29%',
  'Wright St': '47%',
  'Wyoming': '32%',
  'Yale': '57%',
  'Akron': '47%',
  'Alabama': '41%',
  'Arizona': '32%',
  'Arkansas': '32%',
  'Auburn': '30%',
  'Baylor': '32%',
  'Boise St': '31%',
  'Bryant': '53%',
  'Chatt': '43%',
  'Colgate': '37%',
  'Colo St': '31%',
  'Connecticut': '36%',
  'Creighton': '37%',
  'CS Fullerton': '53%',
  'Davidson': '36%',
  'Delaware': '47%',
  'Duke': '33%',
  'Georgia St': '52%',
  'Gonzaga': '32%',
  'Houston': '35%',
  'Illinois': '36%',
  'Indiana': '37%',
  'Iowa': '32%',
  'Iowa St': '39%',
  'Jville St': '46%',
  'Kansas': '33%',
  'Kentucky': '29%'},
 'Loyola-Chi': {'LSU': '50%',
  'Marquette': '50%',
  'Memphis': '43%',
  'Miami FL': '42%',
  'Michigan': '50%',
  'Michigan St': '47%',
  'Montana St': '60%',
  'Murray St': '48%',
  'N Mex St': '52%',
  'Norfolk St': '58%',
  'N Carolina': '48%',
  'Notre Dame': '54%',
  'Ohio St': '47%',
  'Providence': '50%',
  'Purdue': '37%',
  'Richmond': '46%',
  'Rutgers': '43%',
  'S Dakota St': '51%',
  'San Diego St': '48%',
  'San Fran': '44%',
  'Seton Hall': '53%',
  "St Mary's": '39%',
  "St Peter's": '54%',
  'TAM C. Christi': '64%',
  'TCU': '55%',
  'Tennessee': '34%',
  'Texas': '41%',
  'Texas Tech': '38%',
  'TX Southern': '59%',
  'UAB': '52%',
  'UCLA': '40%',
  'USC': '48%',
  'Vermont': '49%',
  'Villanova': '36%',
  'Virginia Tech': '36%',
  'Wisconsin': '50%',
  'Wright St': '57%',
  'Wyoming': '47%',
  'Yale': '52%',
  'Akron': '69%',
  'Alabama': '49%',
  'Arizona': '34%',
  'Arkansas': '44%',
  'Auburn': '32%',
  'Baylor': '34%',
  'Boise St': '33%',
  'Bryant': '67%',
  'Chatt': '52%',
  'Colgate': '62%',
  'Colo St': '36%',
  'Connecticut': '41%',
  'Creighton': '46%',
  'CS Fullerton': '72%',
  'Davidson': '49%',
  'Delaware': '67%',
  'Duke': '32%',
  'Georgia St': '68%',
  'Gonzaga': '33%',
  'Houston': '35%',
  'Illinois': '43%',
  'Indiana': '46%',
  'Iowa': '38%',
  'Iowa St': '45%',
  'Jville St': '68%',
  'Kansas': '32%',
  'Kentucky': '30%',
  'Longwood': '71%'},
 'LSU': {'Marquette': '50%',
  'Memphis': '55%',
  'Miami FL': '51%',
  'Michigan': '53%',
  'Michigan St': '45%',
  'Montana St': '65%',
  'Murray St': '61%',
  'N Mex St': '68%',
  'Norfolk St': '67%',
  'N Carolina': '50%',
  'Notre Dame': '53%',
  'Ohio St': '54%',
  'Providence': '56%',
  'Purdue': '51%',
  'Richmond': '51%',
  'Rutgers': '49%',
  'S Dakota St': '55%',
  'San Diego St': '48%',
  'San Fran': '52%',
  'Seton Hall': '60%',
  "St Mary's": '39%',
  "St Peter's": '66%',
  'TAM C. Christi': '72%',
  'TCU': '57%',
  'Tennessee': '34%',
  'Texas': '50%',
  'Texas Tech': '45%',
  'TX Southern': '68%',
  'UAB': '54%',
  'UCLA': '36%',
  'USC': '49%',
  'Vermont': '54%',
  'Villanova': '40%',
  'Virginia Tech': '50%',
  'Wisconsin': '53%',
  'Wright St': '62%',
  'Wyoming': '65%',
  'Yale': '70%',
  'Akron': '66%',
  'Alabama': '50%',
  'Arizona': '47%',
  'Arkansas': '53%',
  'Auburn': '40%',
  'Baylor': '41%',
  'Boise St': '44%',
  'Bryant': '67%',
  'Chatt': '56%',
  'Colgate': '61%',
  'Colo St': '48%',
  'Connecticut': '52%',
  'Creighton': '49%',
  'CS Fullerton': '69%',
  'Davidson': '55%',
  'Delaware': '66%',
  'Duke': '45%',
  'Georgia St': '72%',
  'Gonzaga': '42%',
  'Houston': '44%',
  'Illinois': '51%',
  'Indiana': '57%',
  'Iowa': '50%',
  'Iowa St': '58%',
  'Jville St': '62%',
  'Kansas': '37%',
  'Kentucky': '37%',
  'Longwood': '68%',
  'Loyola-Chi': '49%'},
 'Marquette': {'Memphis': '53%',
  'Miami FL': '52%',
  'Michigan': '54%',
  'Michigan St': '45%',
  'Montana St': '64%',
  'Murray St': '50%',
  'N Mex St': '67%',
  'Norfolk St': '68%',
  'N Carolina': '53%',
  'Notre Dame': '56%',
  'Ohio St': '52%',
  'Providence': '51%',
  'Purdue': '40%',
  'Richmond': '55%',
  'Rutgers': '50%',
  'S Dakota St': '61%',
  'San Diego St': '44%',
  'San Fran': '44%',
  'Seton Hall': '59%',
  "St Mary's": '36%',
  "St Peter's": '66%',
  'TAM C. Christi': '70%',
  'TCU': '52%',
  'Tennessee': '31%',
  'Texas': '51%',
  'Texas Tech': '41%',
  'TX Southern': '66%',
  'UAB': '54%',
  'UCLA': '39%',
  'USC': '55%',
  'Vermont': '59%',
  'Villanova': '32%',
  'Virginia Tech': '44%',
  'Wisconsin': '38%',
  'Wright St': '64%',
  'Wyoming': '64%',
  'Yale': '68%',
  'Akron': '66%',
  'Alabama': '49%',
  'Arizona': '45%',
  'Arkansas': '48%',
  'Auburn': '38%',
  'Baylor': '47%',
  'Boise St': '41%',
  'Bryant': '69%',
  'Chatt': '63%',
  'Colgate': '66%',
  'Colo St': '39%',
  'Connecticut': '48%',
  'Creighton': '52%',
  'CS Fullerton': '72%',
  'Davidson': '51%',
  'Delaware': '70%',
  'Duke': '45%',
  'Georgia St': '77%',
  'Gonzaga': '37%',
  'Houston': '47%',
  'Illinois': '46%',
  'Indiana': '61%',
  'Iowa': '49%',
  'Iowa St': '54%',
  'Jville St': '71%',
  'Kansas': '37%',
  'Kentucky': '38%',
  'Longwood': '63%',
  'Loyola-Chi': '49%',
  'LSU': '49%'},
 'Memphis': {'Miami FL': '55%',
  'Michigan': '46%',
  'Michigan St': '44%',
  'Montana St': '62%',
  'Murray St': '56%',
  'N Mex St': '69%',
  'Norfolk St': '66%',
  'N Carolina': '58%',
  'Notre Dame': '54%',
  'Ohio St': '51%',
  'Providence': '52%',
  'Purdue': '35%',
  'Richmond': '49%',
  'Rutgers': '49%',
  'S Dakota St': '53%',
  'San Diego St': '40%',
  'San Fran': '49%',
  'Seton Hall': '58%',
  "St Mary's": '38%',
  "St Peter's": '64%',
  'TAM C. Christi': '68%',
  'TCU': '47%',
  'Tennessee': '31%',
  'Texas': '48%',
  'Texas Tech': '42%',
  'TX Southern': '65%',
  'UAB': '56%',
  'UCLA': '40%',
  'USC': '51%',
  'Vermont': '51%',
  'Villanova': '32%',
  'Virginia Tech': '48%',
  'Wisconsin': '46%',
  'Wright St': '63%',
  'Wyoming': '61%',
  'Yale': '71%',
  'Akron': '70%',
  'Alabama': '46%',
  'Arizona': '44%',
  'Arkansas': '44%',
  'Auburn': '34%',
  'Baylor': '46%',
  'Boise St': '49%',
  'Bryant': '67%',
  'Chatt': '57%',
  'Colgate': '63%',
  'Colo St': '47%',
  'Connecticut': '48%',
  'Creighton': '46%',
  'CS Fullerton': '72%',
  'Davidson': '50%',
  'Delaware': '68%',
  'Duke': '45%',
  'Georgia St': '68%',
  'Gonzaga': '38%',
  'Houston': '45%',
  'Illinois': '45%',
  'Indiana': '57%',
  'Iowa': '48%',
  'Iowa St': '55%',
  'Jville St': '66%',
  'Kansas': '34%',
  'Kentucky': '34%',
  'Longwood': '69%',
  'Loyola-Chi': '56%',
  'LSU': '44%',
  'Marquette': '46%'},
 'Miami FL': {'Michigan': '41%',
  'Michigan St': '40%',
  'Montana St': '58%',
  'Murray St': '46%',
  'N Mex St': '61%',
  'Norfolk St': '61%',
  'N Carolina': '54%',
  'Notre Dame': '56%',
  'Ohio St': '36%',
  'Providence': '38%',
  'Purdue': '33%',
  'Richmond': '49%',
  'Rutgers': '50%',
  'S Dakota St': '55%',
  'San Diego St': '38%',
  'San Fran': '41%',
  'Seton Hall': '44%',
  "St Mary's": '34%',
  "St Peter's": '59%',
  'TAM C. Christi': '66%',
  'TCU': '44%',
  'Tennessee': '23%',
  'Texas': '44%',
  'Texas Tech': '35%',
  'TX Southern': '60%',
  'UAB': '55%',
  'UCLA': '36%',
  'USC': '47%',
  'Vermont': '53%',
  'Villanova': '30%',
  'Virginia Tech': '36%',
  'Wisconsin': '33%',
  'Wright St': '64%',
  'Wyoming': '57%',
  'Yale': '65%',
  'Akron': '69%',
  'Alabama': '47%',
  'Arizona': '31%',
  'Arkansas': '33%',
  'Auburn': '32%',
  'Baylor': '32%',
  'Boise St': '32%',
  'Bryant': '65%',
  'Chatt': '57%',
  'Colgate': '58%',
  'Colo St': '30%',
  'Connecticut': '41%',
  'Creighton': '40%',
  'CS Fullerton': '73%',
  'Davidson': '49%',
  'Delaware': '68%',
  'Duke': '41%',
  'Georgia St': '75%',
  'Gonzaga': '32%',
  'Houston': '43%',
  'Illinois': '42%',
  'Indiana': '46%',
  'Iowa': '47%',
  'Iowa St': '43%',
  'Jville St': '70%',
  'Kansas': '29%',
  'Kentucky': '31%',
  'Longwood': '65%',
  'Loyola-Chi': '57%',
  'LSU': '48%',
  'Marquette': '47%',
  'Memphis': '44%'},
 'Michigan': {'Michigan St': '46%',
  'Montana St': '58%',
  'Murray St': '49%',
  'N Mex St': '58%',
  'Norfolk St': '59%',
  'N Carolina': '57%',
  'Notre Dame': '52%',
  'Ohio St': '53%',
  'Providence': '53%',
  'Purdue': '42%',
  'Richmond': '50%',
  'Rutgers': '41%',
  'S Dakota St': '59%',
  'San Diego St': '48%',
  'San Fran': '52%',
  'Seton Hall': '53%',
  "St Mary's": '41%',
  "St Peter's": '58%',
  'TAM C. Christi': '60%',
  'TCU': '52%',
  'Tennessee': '32%',
  'Texas': '47%',
  'Texas Tech': '40%',
  'TX Southern': '61%',
  'UAB': '49%',
  'UCLA': '41%',
  'USC': '54%',
  'Vermont': '57%',
  'Villanova': '34%',
  'Virginia Tech': '48%',
  'Wisconsin': '51%',
  'Wright St': '62%',
  'Wyoming': '55%',
  'Yale': '62%',
  'Akron': '71%',
  'Alabama': '49%',
  'Arizona': '42%',
  'Arkansas': '44%',
  'Auburn': '38%',
  'Baylor': '39%',
  'Boise St': '49%',
  'Bryant': '62%',
  'Chatt': '63%',
  'Colgate': '63%',
  'Colo St': '47%',
  'Connecticut': '42%',
  'Creighton': '54%',
  'CS Fullerton': '70%',
  'Davidson': '55%',
  'Delaware': '68%',
  'Duke': '42%',
  'Georgia St': '66%',
  'Gonzaga': '35%',
  'Houston': '42%',
  'Illinois': '36%',
  'Indiana': '54%',
  'Iowa': '43%',
  'Iowa St': '51%',
  'Jville St': '68%',
  'Kansas': '33%',
  'Kentucky': '36%',
  'Longwood': '66%',
  'Loyola-Chi': '49%',
  'LSU': '46%',
  'Marquette': '45%',
  'Memphis': '53%',
  'Miami FL': '58%'},
 'Michigan St': {'Montana St': '59%',
  'Murray St': '53%',
  'N Mex St': '67%',
  'Norfolk St': '64%',
  'N Carolina': '59%',
  'Notre Dame': '60%',
  'Ohio St': '57%',
  'Providence': '57%',
  'Purdue': '44%',
  'Richmond': '57%',
  'Rutgers': '50%',
  'S Dakota St': '55%',
  'San Diego St': '52%',
  'San Fran': '55%',
  'Seton Hall': '61%',
  "St Mary's": '43%',
  "St Peter's": '59%',
  'TAM C. Christi': '62%',
  'TCU': '60%',
  'Tennessee': '35%',
  'Texas': '47%',
  'Texas Tech': '44%',
  'TX Southern': '62%',
  'UAB': '49%',
  'UCLA': '44%',
  'USC': '54%',
  'Vermont': '58%',
  'Villanova': '37%',
  'Virginia Tech': '51%',
  'Wisconsin': '55%',
  'Wright St': '65%',
  'Wyoming': '65%',
  'Yale': '67%',
  'Akron': '71%',
  'Alabama': '51%',
  'Arizona': '45%',
  'Arkansas': '49%',
  'Auburn': '42%',
  'Baylor': '48%',
  'Boise St': '53%',
  'Bryant': '68%',
  'Chatt': '59%',
  'Colgate': '66%',
  'Colo St': '44%',
  'Connecticut': '53%',
  'Creighton': '54%',
  'CS Fullerton': '74%',
  'Davidson': '51%',
  'Delaware': '72%',
  'Duke': '51%',
  'Georgia St': '69%',
  'Gonzaga': '37%',
  'Houston': '46%',
  'Illinois': '56%',
  'Indiana': '60%',
  'Iowa': '47%',
  'Iowa St': '58%',
  'Jville St': '73%',
  'Kansas': '45%',
  'Kentucky': '44%',
  'Longwood': '68%',
  'Loyola-Chi': '52%',
  'LSU': '54%',
  'Marquette': '54%',
  'Memphis': '55%',
  'Miami FL': '59%',
  'Michigan': '53%'},
 'Montana St': {'Murray St': '31%',
  'N Mex St': '33%',
  'Norfolk St': '55%',
  'N Carolina': '31%',
  'Notre Dame': '34%',
  'Ohio St': '30%',
  'Providence': '30%',
  'Purdue': '24%',
  'Richmond': '33%',
  'Rutgers': '26%',
  'S Dakota St': '27%',
  'San Diego St': '31%',
  'San Fran': '32%',
  'Seton Hall': '28%',
  "St Mary's": '26%',
  "St Peter's": '47%',
  'TAM C. Christi': '58%',
  'TCU': '33%',
  'Tennessee': '27%',
  'Texas': '35%',
  'Texas Tech': '27%',
  'TX Southern': '58%',
  'UAB': '31%',
  'UCLA': '26%',
  'USC': '32%',
  'Vermont': '39%',
  'Villanova': '23%',
  'Virginia Tech': '35%',
  'Wisconsin': '29%',
  'Wright St': '52%',
  'Wyoming': '30%',
  'Yale': '47%',
  'Akron': '43%',
  'Alabama': '36%',
  'Arizona': '35%',
  'Arkansas': '31%',
  'Auburn': '28%',
  'Baylor': '33%',
  'Boise St': '36%',
  'Bryant': '55%',
  'Chatt': '43%',
  'Colgate': '46%',
  'Colo St': '35%',
  'Connecticut': '34%',
  'Creighton': '43%',
  'CS Fullerton': '49%',
  'Davidson': '37%',
  'Delaware': '47%',
  'Duke': '34%',
  'Georgia St': '51%',
  'Gonzaga': '34%',
  'Houston': '32%',
  'Illinois': '40%',
  'Indiana': '35%',
  'Iowa': '32%',
  'Iowa St': '40%',
  'Jville St': '50%',
  'Kansas': '31%',
  'Kentucky': '30%',
  'Longwood': '52%',
  'Loyola-Chi': '39%',
  'LSU': '34%',
  'Marquette': '35%',
  'Memphis': '37%',
  'Miami FL': '41%',
  'Michigan': '41%',
  'Michigan St': '40%'},
 'Murray St': {'N Mex St': '53%',
  'Norfolk St': '63%',
  'N Carolina': '52%',
  'Notre Dame': '56%',
  'Ohio St': '50%',
  'Providence': '52%',
  'Purdue': '44%',
  'Richmond': '44%',
  'Rutgers': '46%',
  'S Dakota St': '51%',
  'San Diego St': '47%',
  'San Fran': '42%',
  'Seton Hall': '49%',
  "St Mary's": '44%',
  "St Peter's": '56%',
  'TAM C. Christi': '66%',
  'TCU': '54%',
  'Tennessee': '30%',
  'Texas': '41%',
  'Texas Tech': '39%',
  'TX Southern': '63%',
  'UAB': '50%',
  'UCLA': '42%',
  'USC': '46%',
  'Vermont': '57%',
  'Villanova': '35%',
  'Virginia Tech': '47%',
  'Wisconsin': '47%',
  'Wright St': '62%',
  'Wyoming': '51%',
  'Yale': '57%',
  'Akron': '74%',
  'Alabama': '49%',
  'Arizona': '36%',
  'Arkansas': '38%',
  'Auburn': '34%',
  'Baylor': '36%',
  'Boise St': '43%',
  'Bryant': '72%',
  'Chatt': '52%',
  'Colgate': '68%',
  'Colo St': '45%',
  'Connecticut': '42%',
  'Creighton': '49%',
  'CS Fullerton': '76%',
  'Davidson': '42%',
  'Delaware': '63%',
  'Duke': '39%',
  'Georgia St': '73%',
  'Gonzaga': '38%',
  'Houston': '40%',
  'Illinois': '42%',
  'Indiana': '51%',
  'Iowa': '36%',
  'Iowa St': '49%',
  'Jville St': '70%',
  'Kansas': '35%',
  'Kentucky': '37%',
  'Longwood': '75%',
  'Loyola-Chi': '51%',
  'LSU': '38%',
  'Marquette': '49%',
  'Memphis': '43%',
  'Miami FL': '53%',
  'Michigan': '50%',
  'Michigan St': '46%',
  'Montana St': '68%'},
 'N Mex St': {'Norfolk St': '54%',
  'N Carolina': '31%',
  'Notre Dame': '42%',
  'Ohio St': '31%',
  'Providence': '37%',
  'Purdue': '25%',
  'Richmond': '46%',
  'Rutgers': '37%',
  'S Dakota St': '45%',
  'San Diego St': '34%',
  'San Fran': '30%',
  'Seton Hall': '30%',
  "St Mary's": '34%',
  "St Peter's": '53%',
  'TAM C. Christi': '58%',
  'TCU': '35%',
  'Tennessee': '23%',
  'Texas': '35%',
  'Texas Tech': '31%',
  'TX Southern': '56%',
  'UAB': '32%',
  'UCLA': '36%',
  'USC': '38%',
  'Vermont': '41%',
  'Villanova': '25%',
  'Virginia Tech': '34%',
  'Wisconsin': '32%',
  'Wright St': '57%',
  'Wyoming': '40%',
  'Yale': '60%',
  'Akron': '67%',
  'Alabama': '40%',
  'Arizona': '30%',
  'Arkansas': '34%',
  'Auburn': '33%',
  'Baylor': '32%',
  'Boise St': '30%',
  'Bryant': '64%',
  'Chatt': '42%',
  'Colgate': '60%',
  'Colo St': '34%',
  'Connecticut': '31%',
  'Creighton': '34%',
  'CS Fullerton': '66%',
  'Davidson': '38%',
  'Delaware': '59%',
  'Duke': '37%',
  'Georgia St': '62%',
  'Gonzaga': '34%',
  'Houston': '39%',
  'Illinois': '32%',
  'Indiana': '37%',
  'Iowa': '30%',
  'Iowa St': '37%',
  'Jville St': '67%',
  'Kansas': '34%',
  'Kentucky': '35%',
  'Longwood': '64%',
  'Loyola-Chi': '47%',
  'LSU': '31%',
  'Marquette': '32%',
  'Memphis': '30%',
  'Miami FL': '38%',
  'Michigan': '41%',
  'Michigan St': '32%',
  'Montana St': '66%',
  'Murray St': '46%'},
 'Norfolk St': {'N Carolina': '26%',
  'Notre Dame': '33%',
  'Ohio St': '31%',
  'Providence': '26%',
  'Purdue': '21%',
  'Richmond': '28%',
  'Rutgers': '28%',
  'S Dakota St': '26%',
  'San Diego St': '28%',
  'San Fran': '26%',
  'Seton Hall': '28%',
  "St Mary's": '29%',
  "St Peter's": '40%',
  'TAM C. Christi': '50%',
  'TCU': '31%',
  'Tennessee': '19%',
  'Texas': '31%',
  'Texas Tech': '24%',
  'TX Southern': '45%',
  'UAB': '23%',
  'UCLA': '20%',
  'USC': '26%',
  'Vermont': '31%',
  'Villanova': '23%',
  'Virginia Tech': '31%',
  'Wisconsin': '23%',
  'Wright St': '38%',
  'Wyoming': '28%',
  'Yale': '47%',
  'Akron': '42%',
  'Alabama': '33%',
  'Arizona': '27%',
  'Arkansas': '31%',
  'Auburn': '28%',
  'Baylor': '27%',
  'Boise St': '30%',
  'Bryant': '49%',
  'Chatt': '40%',
  'Colgate': '42%',
  'Colo St': '30%',
  'Connecticut': '31%',
  'Creighton': '35%',
  'CS Fullerton': '53%',
  'Davidson': '33%',
  'Delaware': '38%',
  'Duke': '29%',
  'Georgia St': '45%',
  'Gonzaga': '30%',
  'Houston': '34%',
  'Illinois': '35%',
  'Indiana': '35%',
  'Iowa': '32%',
  'Iowa St': '38%',
  'Jville St': '40%',
  'Kansas': '31%',
  'Kentucky': '28%',
  'Longwood': '41%',
  'Loyola-Chi': '41%',
  'LSU': '32%',
  'Marquette': '31%',
  'Memphis': '33%',
  'Miami FL': '38%',
  'Michigan': '40%',
  'Michigan St': '35%',
  'Montana St': '44%',
  'Murray St': '36%',
  'N Mex St': '45%'},
 'N Carolina': {'Notre Dame': '57%',
  'Ohio St': '46%',
  'Providence': '47%',
  'Purdue': '32%',
  'Richmond': '50%',
  'Rutgers': '48%',
  'S Dakota St': '48%',
  'San Diego St': '41%',
  'San Fran': '39%',
  'Seton Hall': '48%',
  "St Mary's": '33%',
  "St Peter's": '63%',
  'TAM C. Christi': '60%',
  'TCU': '47%',
  'Tennessee': '32%',
  'Texas': '44%',
  'Texas Tech': '38%',
  'TX Southern': '62%',
  'UAB': '44%',
  'UCLA': '38%',
  'USC': '49%',
  'Vermont': '54%',
  'Villanova': '34%',
  'Virginia Tech': '48%',
  'Wisconsin': '43%',
  'Wright St': '58%',
  'Wyoming': '57%',
  'Yale': '61%',
  'Akron': '69%',
  'Alabama': '42%',
  'Arizona': '35%',
  'Arkansas': '44%',
  'Auburn': '29%',
  'Baylor': '29%',
  'Boise St': '33%',
  'Bryant': '70%',
  'Chatt': '57%',
  'Colgate': '62%',
  'Colo St': '36%',
  'Connecticut': '37%',
  'Creighton': '44%',
  'CS Fullerton': '69%',
  'Davidson': '51%',
  'Delaware': '70%',
  'Duke': '39%',
  'Georgia St': '71%',
  'Gonzaga': '32%',
  'Houston': '36%',
  'Illinois': '38%',
  'Indiana': '61%',
  'Iowa': '42%',
  'Iowa St': '56%',
  'Jville St': '71%',
  'Kansas': '27%',
  'Kentucky': '26%',
  'Longwood': '65%',
  'Loyola-Chi': '51%',
  'LSU': '49%',
  'Marquette': '46%',
  'Memphis': '41%',
  'Miami FL': '45%',
  'Michigan': '42%',
  'Michigan St': '40%',
  'Montana St': '68%',
  'Murray St': '47%',
  'N Mex St': '68%',
  'Norfolk St': '73%'},
 'Notre Dame': {'Ohio St': '38%',
  'Providence': '32%',
  'Purdue': '29%',
  'Richmond': '42%',
  'Rutgers': '43%',
  'S Dakota St': '48%',
  'San Diego St': '35%',
  'San Fran': '41%',
  'Seton Hall': '44%',
  "St Mary's": '27%',
  "St Peter's": '61%',
  'TAM C. Christi': '61%',
  'TCU': '42%',
  'Tennessee': '21%',
  'Texas': '38%',
  'Texas Tech': '26%',
  'TX Southern': '61%',
  'UAB': '45%',
  'UCLA': '32%',
  'USC': '42%',
  'Vermont': '52%',
  'Villanova': '22%',
  'Virginia Tech': '35%',
  'Wisconsin': '27%',
  'Wright St': '59%',
  'Wyoming': '47%',
  'Yale': '63%',
  'Akron': '65%',
  'Alabama': '43%',
  'Arizona': '29%',
  'Arkansas': '34%',
  'Auburn': '38%',
  'Baylor': '30%',
  'Boise St': '22%',
  'Bryant': '66%',
  'Chatt': '54%',
  'Colgate': '62%',
  'Colo St': '26%',
  'Connecticut': '39%',
  'Creighton': '36%',
  'CS Fullerton': '68%',
  'Davidson': '42%',
  'Delaware': '69%',
  'Duke': '34%',
  'Georgia St': '69%',
  'Gonzaga': '27%',
  'Houston': '38%',
  'Illinois': '41%',
  'Indiana': '43%',
  'Iowa': '42%',
  'Iowa St': '37%',
  'Jville St': '66%',
  'Kansas': '30%',
  'Kentucky': '27%',
  'Longwood': '67%',
  'Loyola-Chi': '45%',
  'LSU': '46%',
  'Marquette': '43%',
  'Memphis': '45%',
  'Miami FL': '43%',
  'Michigan': '47%',
  'Michigan St': '39%',
  'Montana St': '65%',
  'Murray St': '43%',
  'N Mex St': '57%',
  'Norfolk St': '66%',
  'N Carolina': '42%'},
 'Ohio St': {'Providence': '48%',
  'Purdue': '32%',
  'Richmond': '56%',
  'Rutgers': '48%',
  'S Dakota St': '51%',
  'San Diego St': '40%',
  'San Fran': '40%',
  'Seton Hall': '59%',
  "St Mary's": '33%',
  "St Peter's": '63%',
  'TAM C. Christi': '64%',
  'TCU': '51%',
  'Tennessee': '30%',
  'Texas': '47%',
  'Texas Tech': '36%',
  'TX Southern': '66%',
  'UAB': '49%',
  'UCLA': '30%',
  'USC': '57%',
  'Vermont': '57%',
  'Villanova': '26%',
  'Virginia Tech': '47%',
  'Wisconsin': '41%',
  'Wright St': '61%',
  'Wyoming': '62%',
  'Yale': '68%',
  'Akron': '70%',
  'Alabama': '45%',
  'Arizona': '40%',
  'Arkansas': '43%',
  'Auburn': '35%',
  'Baylor': '35%',
  'Boise St': '47%',
  'Bryant': '64%',
  'Chatt': '61%',
  'Colgate': '65%',
  'Colo St': '50%',
  'Connecticut': '39%',
  'Creighton': '50%',
  'CS Fullerton': '69%',
  'Davidson': '59%',
  'Delaware': '68%',
  'Duke': '40%',
  'Georgia St': '66%',
  'Gonzaga': '31%',
  'Houston': '40%',
  'Illinois': '35%',
  'Indiana': '60%',
  'Iowa': '41%',
  'Iowa St': '53%',
  'Jville St': '65%',
  'Kansas': '36%',
  'Kentucky': '32%',
  'Longwood': '66%',
  'Loyola-Chi': '52%',
  'LSU': '45%',
  'Marquette': '47%',
  'Memphis': '48%',
  'Miami FL': '63%',
  'Michigan': '46%',
  'Michigan St': '42%',
  'Montana St': '69%',
  'Murray St': '49%',
  'N Mex St': '68%',
  'Norfolk St': '68%',
  'N Carolina': '53%',
  'Notre Dame': '61%'},
 'Providence': {'Purdue': '37%',
  'Richmond': '58%',
  'Rutgers': '55%',
  'S Dakota St': '51%',
  'San Diego St': '41%',
  'San Fran': '47%',
  'Seton Hall': '54%',
  "St Mary's": '36%',
  "St Peter's": '64%',
  'TAM C. Christi': '66%',
  'TCU': '52%',
  'Tennessee': '35%',
  'Texas': '48%',
  'Texas Tech': '40%',
  'TX Southern': '67%',
  'UAB': '52%',
  'UCLA': '44%',
  'USC': '61%',
  'Vermont': '58%',
  'Villanova': '34%',
  'Virginia Tech': '56%',
  'Wisconsin': '40%',
  'Wright St': '67%',
  'Wyoming': '63%',
  'Yale': '71%',
  'Akron': '73%',
  'Alabama': '40%',
  'Arizona': '40%',
  'Arkansas': '48%',
  'Auburn': '38%',
  'Baylor': '40%',
  'Boise St': '43%',
  'Bryant': '64%',
  'Chatt': '57%',
  'Colgate': '69%',
  'Colo St': '41%',
  'Connecticut': '41%',
  'Creighton': '53%',
  'CS Fullerton': '74%',
  'Davidson': '53%',
  'Delaware': '73%',
  'Duke': '38%',
  'Georgia St': '69%',
  'Gonzaga': '37%',
  'Houston': '45%',
  'Illinois': '39%',
  'Indiana': '60%',
  'Iowa': '39%',
  'Iowa St': '56%',
  'Jville St': '72%',
  'Kansas': '40%',
  'Kentucky': '43%',
  'Longwood': '68%',
  'Loyola-Chi': '49%',
  'LSU': '43%',
  'Marquette': '48%',
  'Memphis': '47%',
  'Miami FL': '61%',
  'Michigan': '46%',
  'Michigan St': '42%',
  'Montana St': '69%',
  'Murray St': '47%',
  'N Mex St': '62%',
  'Norfolk St': '73%',
  'N Carolina': '52%',
  'Notre Dame': '67%',
  'Ohio St': '51%'},
 'Purdue': {'Richmond': '63%',
  'Rutgers': '59%',
  'S Dakota St': '58%',
  'San Diego St': '51%',
  'San Fran': '57%',
  'Seton Hall': '65%',
  "St Mary's": '56%',
  "St Peter's": '57%',
  'TAM C. Christi': '63%',
  'TCU': '66%',
  'Tennessee': '50%',
  'Texas': '56%',
  'Texas Tech': '48%',
  'TX Southern': '62%',
  'UAB': '52%',
  'UCLA': '58%',
  'USC': '62%',
  'Vermont': '56%',
  'Villanova': '45%',
  'Virginia Tech': '60%',
  'Wisconsin': '55%',
  'Wright St': '67%',
  'Wyoming': '63%',
  'Yale': '68%',
  'Akron': '78%',
  'Alabama': '53%',
  'Arizona': '47%',
  'Arkansas': '65%',
  'Auburn': '51%',
  'Baylor': '51%',
  'Boise St': '54%',
  'Bryant': '67%',
  'Chatt': '62%',
  'Colgate': '71%',
  'Colo St': '56%',
  'Connecticut': '63%',
  'Creighton': '57%',
  'CS Fullerton': '75%',
  'Davidson': '61%',
  'Delaware': '77%',
  'Duke': '51%',
  'Georgia St': '69%',
  'Gonzaga': '42%',
  'Houston': '49%',
  'Illinois': '60%',
  'Indiana': '74%',
  'Iowa': '51%',
  'Iowa St': '67%',
  'Jville St': '76%',
  'Kansas': '46%',
  'Kentucky': '43%',
  'Longwood': '74%',
  'Loyola-Chi': '62%',
  'LSU': '48%',
  'Marquette': '59%',
  'Memphis': '64%',
  'Miami FL': '66%',
  'Michigan': '57%',
  'Michigan St': '55%',
  'Montana St': '75%',
  'Murray St': '55%',
  'N Mex St': '74%',
  'Norfolk St': '78%',
  'N Carolina': '67%',
  'Notre Dame': '70%',
  'Ohio St': '67%',
  'Providence': '62%'},
 'Richmond': {'Rutgers': '42%',
  'S Dakota St': '49%',
  'San Diego St': '36%',
  'San Fran': '40%',
  'Seton Hall': '42%',
  "St Mary's": '36%',
  "St Peter's": '61%',
  'TAM C. Christi': '68%',
  'TCU': '43%',
  'Tennessee': '32%',
  'Texas': '48%',
  'Texas Tech': '38%',
  'TX Southern': '62%',
  'UAB': '43%',
  'UCLA': '41%',
  'USC': '44%',
  'Vermont': '49%',
  'Villanova': '30%',
  'Virginia Tech': '36%',
  'Wisconsin': '37%',
  'Wright St': '64%',
  'Wyoming': '55%',
  'Yale': '68%',
  'Akron': '66%',
  'Alabama': '49%',
  'Arizona': '38%',
  'Arkansas': '41%',
  'Auburn': '38%',
  'Baylor': '35%',
  'Boise St': '34%',
  'Bryant': '67%',
  'Chatt': '48%',
  'Colgate': '65%',
  'Colo St': '41%',
  'Connecticut': '44%',
  'Creighton': '44%',
  'CS Fullerton': '73%',
  'Davidson': '51%',
  'Delaware': '71%',
  'Duke': '43%',
  'Georgia St': '78%',
  'Gonzaga': '35%',
  'Houston': '45%',
  'Illinois': '40%',
  'Indiana': '54%',
  'Iowa': '42%',
  'Iowa St': '54%',
  'Jville St': '71%',
  'Kansas': '34%',
  'Kentucky': '36%',
  'Longwood': '64%',
  'Loyola-Chi': '53%',
  'LSU': '48%',
  'Marquette': '44%',
  'Memphis': '50%',
  'Miami FL': '50%',
  'Michigan': '49%',
  'Michigan St': '42%',
  'Montana St': '66%',
  'Murray St': '55%',
  'N Mex St': '53%',
  'Norfolk St': '71%',
  'N Carolina': '49%',
  'Notre Dame': '57%',
  'Ohio St': '43%',
  'Providence': '41%',
  'Purdue': '36%'},
 'Rutgers': {'S Dakota St': '53%',
  'San Diego St': '32%',
  'San Fran': '37%',
  'Seton Hall': '45%',
  "St Mary's": '26%',
  "St Peter's": '68%',
  'TAM C. Christi': '69%',
  'TCU': '46%',
  'Tennessee': '28%',
  'Texas': '34%',
  'Texas Tech': '36%',
  'TX Southern': '65%',
  'UAB': '48%',
  'UCLA': '35%',
  'USC': '44%',
  'Vermont': '56%',
  'Villanova': '30%',
  'Virginia Tech': '41%',
  'Wisconsin': '32%',
  'Wright St': '62%',
  'Wyoming': '48%',
  'Yale': '74%',
  'Akron': '69%',
  'Alabama': '47%',
  'Arizona': '40%',
  'Arkansas': '41%',
  'Auburn': '37%',
  'Baylor': '43%',
  'Boise St': '42%',
  'Bryant': '69%',
  'Chatt': '53%',
  'Colgate': '71%',
  'Colo St': '39%',
  'Connecticut': '49%',
  'Creighton': '45%',
  'CS Fullerton': '74%',
  'Davidson': '51%',
  'Delaware': '73%',
  'Duke': '47%',
  'Georgia St': '71%',
  'Gonzaga': '28%',
  'Houston': '44%',
  'Illinois': '50%',
  'Indiana': '51%',
  'Iowa': '44%',
  'Iowa St': '43%',
  'Jville St': '74%',
  'Kansas': '45%',
  'Kentucky': '41%',
  'Longwood': '66%',
  'Loyola-Chi': '56%',
  'LSU': '50%',
  'Marquette': '49%',
  'Memphis': '50%',
  'Miami FL': '49%',
  'Michigan': '58%',
  'Michigan St': '49%',
  'Montana St': '73%',
  'Murray St': '53%',
  'N Mex St': '62%',
  'Norfolk St': '71%',
  'N Carolina': '51%',
  'Notre Dame': '56%',
  'Ohio St': '51%',
  'Providence': '44%',
  'Purdue': '40%',
  'Richmond': '57%'},
 'S Dakota St': {'San Diego St': '36%',
  'San Fran': '32%',
  'Seton Hall': '35%',
  "St Mary's": '35%',
  "St Peter's": '50%',
  'TAM C. Christi': '58%',
  'TCU': '37%',
  'Tennessee': '31%',
  'Texas': '33%',
  'Texas Tech': '34%',
  'TX Southern': '58%',
  'UAB': '40%',
  'UCLA': '33%',
  'USC': '34%',
  'Vermont': '47%',
  'Villanova': '32%',
  'Virginia Tech': '34%',
  'Wisconsin': '31%',
  'Wright St': '53%',
  'Wyoming': '50%',
  'Yale': '50%',
  'Akron': '64%',
  'Alabama': '41%',
  'Arizona': '33%',
  'Arkansas': '44%',
  'Auburn': '35%',
  'Baylor': '41%',
  'Boise St': '42%',
  'Bryant': '64%',
  'Chatt': '51%',
  'Colgate': '61%',
  'Colo St': '44%',
  'Connecticut': '48%',
  'Creighton': '44%',
  'CS Fullerton': '70%',
  'Davidson': '47%',
  'Delaware': '59%',
  'Duke': '38%',
  'Georgia St': '62%',
  'Gonzaga': '37%',
  'Houston': '41%',
  'Illinois': '47%',
  'Indiana': '46%',
  'Iowa': '36%',
  'Iowa St': '44%',
  'Jville St': '67%',
  'Kansas': '36%',
  'Kentucky': '35%',
  'Longwood': '69%',
  'Loyola-Chi': '48%',
  'LSU': '44%',
  'Marquette': '38%',
  'Memphis': '46%',
  'Miami FL': '44%',
  'Michigan': '40%',
  'Michigan St': '44%',
  'Montana St': '72%',
  'Murray St': '48%',
  'N Mex St': '54%',
  'Norfolk St': '73%',
  'N Carolina': '51%',
  'Notre Dame': '51%',
  'Ohio St': '48%',
  'Providence': '48%',
  'Purdue': '41%',
  'Richmond': '50%',
  'Rutgers': '46%'},
 'San Diego St': {'San Fran': '49%',
  'Seton Hall': '67%',
  "St Mary's": '48%',
  "St Peter's": '68%',
  'TAM C. Christi': '70%',
  'TCU': '64%',
  'Tennessee': '33%',
  'Texas': '60%',
  'Texas Tech': '49%',
  'TX Southern': '68%',
  'UAB': '49%',
  'UCLA': '47%',
  'USC': '54%',
  'Vermont': '59%',
  'Villanova': '35%',
  'Virginia Tech': '59%',
  'Wisconsin': '51%',
  'Wright St': '66%',
  'Wyoming': '62%',
  'Yale': '72%',
  'Akron': '70%',
  'Alabama': '46%',
  'Arizona': '49%',
  'Arkansas': '50%',
  'Auburn': '45%',
  'Baylor': '42%',
  'Boise St': '47%',
  'Bryant': '65%',
  'Chatt': '57%',
  'Colgate': '66%',
  'Colo St': '57%',
  'Connecticut': '49%',
  'Creighton': '53%',
  'CS Fullerton': '74%',
  'Davidson': '55%',
  'Delaware': '70%',
  'Duke': '42%',
  'Georgia St': '74%',
  'Gonzaga': '44%',
  'Houston': '45%',
  'Illinois': '54%',
  'Indiana': '71%',
  'Iowa': '45%',
  'Iowa St': '65%',
  'Jville St': '71%',
  'Kansas': '34%',
  'Kentucky': '44%',
  'Longwood': '68%',
  'Loyola-Chi': '51%',
  'LSU': '51%',
  'Marquette': '55%',
  'Memphis': '59%',
  'Miami FL': '61%',
  'Michigan': '51%',
  'Michigan St': '47%',
  'Montana St': '68%',
  'Murray St': '52%',
  'N Mex St': '65%',
  'Norfolk St': '71%',
  'N Carolina': '58%',
  'Notre Dame': '64%',
  'Ohio St': '59%',
  'Providence': '58%',
  'Purdue': '48%',
  'Richmond': '63%',
  'Rutgers': '67%',
  'S Dakota St': '63%'},
 'San Fran': {'Seton Hall': '60%',
  "St Mary's": '42%',
  "St Peter's": '63%',
  'TAM C. Christi': '68%',
  'TCU': '54%',
  'Tennessee': '38%',
  'Texas': '59%',
  'Texas Tech': '51%',
  'TX Southern': '63%',
  'UAB': '48%',
  'UCLA': '47%',
  'USC': '56%',
  'Vermont': '53%',
  'Villanova': '35%',
  'Virginia Tech': '48%',
  'Wisconsin': '50%',
  'Wright St': '64%',
  'Wyoming': '50%',
  'Yale': '68%',
  'Akron': '76%',
  'Alabama': '51%',
  'Arizona': '39%',
  'Arkansas': '49%',
  'Auburn': '36%',
  'Baylor': '38%',
  'Boise St': '48%',
  'Bryant': '71%',
  'Chatt': '61%',
  'Colgate': '71%',
  'Colo St': '48%',
  'Connecticut': '42%',
  'Creighton': '48%',
  'CS Fullerton': '78%',
  'Davidson': '50%',
  'Delaware': '72%',
  'Duke': '48%',
  'Georgia St': '74%',
  'Gonzaga': '41%',
  'Houston': '47%',
  'Illinois': '41%',
  'Indiana': '62%',
  'Iowa': '44%',
  'Iowa St': '57%',
  'Jville St': '72%',
  'Kansas': '29%',
  'Kentucky': '38%',
  'Longwood': '74%',
  'Loyola-Chi': '55%',
  'LSU': '47%',
  'Marquette': '55%',
  'Memphis': '50%',
  'Miami FL': '58%',
  'Michigan': '47%',
  'Michigan St': '44%',
  'Montana St': '67%',
  'Murray St': '57%',
  'N Mex St': '69%',
  'Norfolk St': '73%',
  'N Carolina': '60%',
  'Notre Dame': '58%',
  'Ohio St': '59%',
  'Providence': '52%',
  'Purdue': '42%',
  'Richmond': '59%',
  'Rutgers': '62%',
  'S Dakota St': '67%',
  'San Diego St': '50%'},
 'Seton Hall': {"St Mary's": '35%',
  "St Peter's": '62%',
  'TAM C. Christi': '68%',
  'TCU': '51%',
  'Tennessee': '31%',
  'Texas': '49%',
  'Texas Tech': '38%',
  'TX Southern': '62%',
  'UAB': '42%',
  'UCLA': '39%',
  'USC': '55%',
  'Vermont': '54%',
  'Villanova': '28%',
  'Virginia Tech': '48%',
  'Wisconsin': '37%',
  'Wright St': '62%',
  'Wyoming': '58%',
  'Yale': '63%',
  'Akron': '67%',
  'Alabama': '41%',
  'Arizona': '38%',
  'Arkansas': '40%',
  'Auburn': '29%',
  'Baylor': '34%',
  'Boise St': '39%',
  'Bryant': '67%',
  'Chatt': '63%',
  'Colgate': '63%',
  'Colo St': '40%',
  'Connecticut': '35%',
  'Creighton': '49%',
  'CS Fullerton': '71%',
  'Davidson': '56%',
  'Delaware': '69%',
  'Duke': '43%',
  'Georgia St': '74%',
  'Gonzaga': '32%',
  'Houston': '37%',
  'Illinois': '31%',
  'Indiana': '49%',
  'Iowa': '43%',
  'Iowa St': '47%',
  'Jville St': '70%',
  'Kansas': '30%',
  'Kentucky': '35%',
  'Longwood': '67%',
  'Loyola-Chi': '46%',
  'LSU': '39%',
  'Marquette': '40%',
  'Memphis': '41%',
  'Miami FL': '55%',
  'Michigan': '46%',
  'Michigan St': '38%',
  'Montana St': '71%',
  'Murray St': '50%',
  'N Mex St': '69%',
  'Norfolk St': '71%',
  'N Carolina': '51%',
  'Notre Dame': '55%',
  'Ohio St': '40%',
  'Providence': '45%',
  'Purdue': '34%',
  'Richmond': '57%',
  'Rutgers': '54%',
  'S Dakota St': '64%',
  'San Diego St': '32%',
  'San Fran': '39%'},
 "St Mary's": {"St Peter's": '66%',
  'TAM C. Christi': '70%',
  'TCU': '60%',
  'Tennessee': '49%',
  'Texas': '65%',
  'Texas Tech': '53%',
  'TX Southern': '69%',
  'UAB': '55%',
  'UCLA': '53%',
  'USC': '58%',
  'Vermont': '57%',
  'Villanova': '44%',
  'Virginia Tech': '56%',
  'Wisconsin': '57%',
  'Wright St': '69%',
  'Wyoming': '57%',
  'Yale': '69%',
  'Akron': '74%',
  'Alabama': '58%',
  'Arizona': '49%',
  'Arkansas': '61%',
  'Auburn': '53%',
  'Baylor': '40%',
  'Boise St': '50%',
  'Bryant': '70%',
  'Chatt': '64%',
  'Colgate': '68%',
  'Colo St': '58%',
  'Connecticut': '53%',
  'Creighton': '59%',
  'CS Fullerton': '76%',
  'Davidson': '61%',
  'Delaware': '74%',
  'Duke': '46%',
  'Georgia St': '77%',
  'Gonzaga': '43%',
  'Houston': '48%',
  'Illinois': '54%',
  'Indiana': '71%',
  'Iowa': '47%',
  'Iowa St': '74%',
  'Jville St': '76%',
  'Kansas': '49%',
  'Kentucky': '37%',
  'Longwood': '71%',
  'Loyola-Chi': '60%',
  'LSU': '60%',
  'Marquette': '63%',
  'Memphis': '61%',
  'Miami FL': '65%',
  'Michigan': '58%',
  'Michigan St': '56%',
  'Montana St': '73%',
  'Murray St': '55%',
  'N Mex St': '65%',
  'Norfolk St': '70%',
  'N Carolina': '66%',
  'Notre Dame': '72%',
  'Ohio St': '66%',
  'Providence': '63%',
  'Purdue': '43%',
  'Richmond': '63%',
  'Rutgers': '73%',
  'S Dakota St': '64%',
  'San Diego St': '51%',
  'San Fran': '57%',
  'Seton Hall': '64%'},
 "St Peter's": {'TAM C. Christi': '53%',
  'TCU': '27%',
  'Tennessee': '17%',
  'Texas': '26%',
  'Texas Tech': '18%',
  'TX Southern': '52%',
  'UAB': '27%',
  'UCLA': '21%',
  'USC': '24%',
  'Vermont': '38%',
  'Villanova': '22%',
  'Virginia Tech': '30%',
  'Wisconsin': '25%',
  'Wright St': '47%',
  'Wyoming': '33%',
  'Yale': '45%',
  'Akron': '44%',
  'Alabama': '33%',
  'Arizona': '35%',
  'Arkansas': '30%',
  'Auburn': '26%',
  'Baylor': '29%',
  'Boise St': '29%',
  'Bryant': '51%',
  'Chatt': '38%',
  'Colgate': '48%',
  'Colo St': '39%',
  'Connecticut': '33%',
  'Creighton': '37%',
  'CS Fullerton': '54%',
  'Davidson': '41%',
  'Delaware': '49%',
  'Duke': '34%',
  'Georgia St': '55%',
  'Gonzaga': '39%',
  'Houston': '35%',
  'Illinois': '37%',
  'Indiana': '38%',
  'Iowa': '34%',
  'Iowa St': '34%',
  'Jville St': '48%',
  'Kansas': '31%',
  'Kentucky': '30%',
  'Longwood': '44%',
  'Loyola-Chi': '45%',
  'LSU': '33%',
  'Marquette': '33%',
  'Memphis': '35%',
  'Miami FL': '40%',
  'Michigan': '41%',
  'Michigan St': '40%',
  'Montana St': '52%',
  'Murray St': '43%',
  'N Mex St': '46%',
  'Norfolk St': '59%',
  'N Carolina': '36%',
  'Notre Dame': '38%',
  'Ohio St': '36%',
  'Providence': '35%',
  'Purdue': '42%',
  'Richmond': '38%',
  'Rutgers': '31%',
  'S Dakota St': '49%',
  'San Diego St': '31%',
  'San Fran': '36%',
  'Seton Hall': '37%',
  "St Mary's": '33%'},
 'TAM C. Christi': {'TCU': '28%',
  'Tennessee': '22%',
  'Texas': '28%',
  'Texas Tech': '21%',
  'TX Southern': '41%',
  'UAB': '23%',
  'UCLA': '20%',
  'USC': '27%',
  'Vermont': '30%',
  'Villanova': '26%',
  'Virginia Tech': '34%',
  'Wisconsin': '26%',
  'Wright St': '34%',
  'Wyoming': '28%',
  'Yale': '32%',
  'Akron': '44%',
  'Alabama': '33%',
  'Arizona': '29%',
  'Arkansas': '31%',
  'Auburn': '25%',
  'Baylor': '27%',
  'Boise St': '26%',
  'Bryant': '46%',
  'Chatt': '34%',
  'Colgate': '39%',
  'Colo St': '30%',
  'Connecticut': '28%',
  'Creighton': '35%',
  'CS Fullerton': '43%',
  'Davidson': '34%',
  'Delaware': '37%',
  'Duke': '32%',
  'Georgia St': '46%',
  'Gonzaga': '31%',
  'Houston': '31%',
  'Illinois': '35%',
  'Indiana': '32%',
  'Iowa': '33%',
  'Iowa St': '35%',
  'Jville St': '44%',
  'Kansas': '28%',
  'Kentucky': '29%',
  'Longwood': '39%',
  'Loyola-Chi': '35%',
  'LSU': '27%',
  'Marquette': '29%',
  'Memphis': '31%',
  'Miami FL': '33%',
  'Michigan': '39%',
  'Michigan St': '37%',
  'Montana St': '41%',
  'Murray St': '33%',
  'N Mex St': '41%',
  'Norfolk St': '49%',
  'N Carolina': '39%',
  'Notre Dame': '38%',
  'Ohio St': '35%',
  'Providence': '33%',
  'Purdue': '36%',
  'Richmond': '31%',
  'Rutgers': '30%',
  'S Dakota St': '41%',
  'San Diego St': '29%',
  'San Fran': '31%',
  'Seton Hall': '31%',
  "St Mary's": '29%',
  "St Peter's": '46%'},
 'TCU': {'Tennessee': '27%',
  'Texas': '48%',
  'Texas Tech': '37%',
  'TX Southern': '64%',
  'UAB': '48%',
  'UCLA': '38%',
  'USC': '49%',
  'Vermont': '57%',
  'Villanova': '30%',
  'Virginia Tech': '48%',
  'Wisconsin': '42%',
  'Wright St': '61%',
  'Wyoming': '56%',
  'Yale': '69%',
  'Akron': '68%',
  'Alabama': '44%',
  'Arizona': '44%',
  'Arkansas': '48%',
  'Auburn': '38%',
  'Baylor': '34%',
  'Boise St': '38%',
  'Bryant': '70%',
  'Chatt': '58%',
  'Colgate': '63%',
  'Colo St': '38%',
  'Connecticut': '45%',
  'Creighton': '47%',
  'CS Fullerton': '70%',
  'Davidson': '52%',
  'Delaware': '67%',
  'Duke': '48%',
  'Georgia St': '71%',
  'Gonzaga': '35%',
  'Houston': '45%',
  'Illinois': '35%',
  'Indiana': '54%',
  'Iowa': '51%',
  'Iowa St': '54%',
  'Jville St': '69%',
  'Kansas': '30%',
  'Kentucky': '31%',
  'Longwood': '64%',
  'Loyola-Chi': '44%',
  'LSU': '42%',
  'Marquette': '47%',
  'Memphis': '52%',
  'Miami FL': '55%',
  'Michigan': '47%',
  'Michigan St': '39%',
  'Montana St': '66%',
  'Murray St': '45%',
  'N Mex St': '64%',
  'Norfolk St': '68%',
  'N Carolina': '52%',
  'Notre Dame': '57%',
  'Ohio St': '48%',
  'Providence': '47%',
  'Purdue': '33%',
  'Richmond': '56%',
  'Rutgers': '53%',
  'S Dakota St': '62%',
  'San Diego St': '35%',
  'San Fran': '45%',
  'Seton Hall': '48%',
  "St Mary's": '39%',
  "St Peter's": '72%',
  'TAM C. Christi': '71%'},
 'Tennessee': {'Texas': '71%',
  'Texas Tech': '60%',
  'TX Southern': '72%',
  'UAB': '63%',
  'UCLA': '61%',
  'USC': '68%',
  'Vermont': '64%',
  'Villanova': '48%',
  'Virginia Tech': '70%',
  'Wisconsin': '60%',
  'Wright St': '69%',
  'Wyoming': '72%',
  'Yale': '73%',
  'Akron': '79%',
  'Alabama': '61%',
  'Arizona': '52%',
  'Arkansas': '63%',
  'Auburn': '54%',
  'Baylor': '50%',
  'Boise St': '56%',
  'Bryant': '77%',
  'Chatt': '68%',
  'Colgate': '76%',
  'Colo St': '61%',
  'Connecticut': '61%',
  'Creighton': '66%',
  'CS Fullerton': '82%',
  'Davidson': '63%',
  'Delaware': '78%',
  'Duke': '51%',
  'Georgia St': '79%',
  'Gonzaga': '43%',
  'Houston': '49%',
  'Illinois': '63%',
  'Indiana': '77%',
  'Iowa': '62%',
  'Iowa St': '73%',
  'Jville St': '78%',
  'Kansas': '51%',
  'Kentucky': '48%',
  'Longwood': '81%',
  'Loyola-Chi': '65%',
  'LSU': '65%',
  'Marquette': '68%',
  'Memphis': '68%',
  'Miami FL': '76%',
  'Michigan': '67%',
  'Michigan St': '64%',
  'Montana St': '72%',
  'Murray St': '69%',
  'N Mex St': '76%',
  'Norfolk St': '80%',
  'N Carolina': '67%',
  'Notre Dame': '78%',
  'Ohio St': '69%',
  'Providence': '64%',
  'Purdue': '49%',
  'Richmond': '67%',
  'Rutgers': '71%',
  'S Dakota St': '68%',
  'San Diego St': '66%',
  'San Fran': '61%',
  'Seton Hall': '68%',
  "St Mary's": '50%',
  "St Peter's": '82%',
  'TAM C. Christi': '77%',
  'TCU': '72%'},
 'Texas': {'Texas Tech': '38%',
  'TX Southern': '65%',
  'UAB': '47%',
  'UCLA': '30%',
  'USC': '52%',
  'Vermont': '59%',
  'Villanova': '34%',
  'Virginia Tech': '52%',
  'Wisconsin': '43%',
  'Wright St': '57%',
  'Wyoming': '55%',
  'Yale': '66%',
  'Akron': '69%',
  'Alabama': '49%',
  'Arizona': '43%',
  'Arkansas': '51%',
  'Auburn': '34%',
  'Baylor': '32%',
  'Boise St': '43%',
  'Bryant': '65%',
  'Chatt': '60%',
  'Colgate': '61%',
  'Colo St': '53%',
  'Connecticut': '38%',
  'Creighton': '55%',
  'CS Fullerton': '70%',
  'Davidson': '62%',
  'Delaware': '68%',
  'Duke': '43%',
  'Georgia St': '69%',
  'Gonzaga': '42%',
  'Houston': '40%',
  'Illinois': '44%',
  'Indiana': '61%',
  'Iowa': '44%',
  'Iowa St': '53%',
  'Jville St': '62%',
  'Kansas': '35%',
  'Kentucky': '32%',
  'Longwood': '67%',
  'Loyola-Chi': '58%',
  'LSU': '49%',
  'Marquette': '48%',
  'Memphis': '51%',
  'Miami FL': '55%',
  'Michigan': '52%',
  'Michigan St': '52%',
  'Montana St': '64%',
  'Murray St': '58%',
  'N Mex St': '64%',
  'Norfolk St': '68%',
  'N Carolina': '55%',
  'Notre Dame': '61%',
  'Ohio St': '52%',
  'Providence': '51%',
  'Purdue': '43%',
  'Richmond': '51%',
  'Rutgers': '65%',
  'S Dakota St': '66%',
  'San Diego St': '39%',
  'San Fran': '40%',
  'Seton Hall': '50%',
  "St Mary's": '34%',
  "St Peter's": '73%',
  'TAM C. Christi': '71%',
  'TCU': '51%',
  'Tennessee': '28%'},
 'Texas Tech': {'TX Southern': '69%',
  'UAB': '62%',
  'UCLA': '57%',
  'USC': '63%',
  'Vermont': '64%',
  'Villanova': '49%',
  'Virginia Tech': '65%',
  'Wisconsin': '56%',
  'Wright St': '68%',
  'Wyoming': '65%',
  'Yale': '72%',
  'Akron': '78%',
  'Alabama': '54%',
  'Arizona': '48%',
  'Arkansas': '56%',
  'Auburn': '45%',
  'Baylor': '44%',
  'Boise St': '53%',
  'Bryant': '71%',
  'Chatt': '65%',
  'Colgate': '72%',
  'Colo St': '56%',
  'Connecticut': '51%',
  'Creighton': '56%',
  'CS Fullerton': '77%',
  'Davidson': '61%',
  'Delaware': '74%',
  'Duke': '49%',
  'Georgia St': '72%',
  'Gonzaga': '45%',
  'Houston': '41%',
  'Illinois': '58%',
  'Indiana': '67%',
  'Iowa': '52%',
  'Iowa St': '68%',
  'Jville St': '72%',
  'Kansas': '40%',
  'Kentucky': '42%',
  'Longwood': '77%',
  'Loyola-Chi': '61%',
  'LSU': '54%',
  'Marquette': '58%',
  'Memphis': '57%',
  'Miami FL': '64%',
  'Michigan': '59%',
  'Michigan St': '55%',
  'Montana St': '72%',
  'Murray St': '60%',
  'N Mex St': '68%',
  'Norfolk St': '75%',
  'N Carolina': '61%',
  'Notre Dame': '73%',
  'Ohio St': '63%',
  'Providence': '59%',
  'Purdue': '51%',
  'Richmond': '61%',
  'Rutgers': '63%',
  'S Dakota St': '65%',
  'San Diego St': '50%',
  'San Fran': '48%',
  'Seton Hall': '61%',
  "St Mary's": '46%',
  "St Peter's": '81%',
  'TAM C. Christi': '78%',
  'TCU': '62%',
  'Tennessee': '39%',
  'Texas': '61%'},
 'TX Southern': {'UAB': '24%',
  'UCLA': '25%',
  'USC': '25%',
  'Vermont': '36%',
  'Villanova': '23%',
  'Virginia Tech': '31%',
  'Wisconsin': '29%',
  'Wright St': '40%',
  'Wyoming': '35%',
  'Yale': '42%',
  'Akron': '42%',
  'Alabama': '32%',
  'Arizona': '33%',
  'Arkansas': '31%',
  'Auburn': '27%',
  'Baylor': '30%',
  'Boise St': '31%',
  'Bryant': '39%',
  'Chatt': '40%',
  'Colgate': '45%',
  'Colo St': '37%',
  'Connecticut': '30%',
  'Creighton': '35%',
  'CS Fullerton': '45%',
  'Davidson': '36%',
  'Delaware': '46%',
  'Duke': '35%',
  'Georgia St': '44%',
  'Gonzaga': '34%',
  'Houston': '36%',
  'Illinois': '36%',
  'Indiana': '37%',
  'Iowa': '31%',
  'Iowa St': '32%',
  'Jville St': '46%',
  'Kansas': '32%',
  'Kentucky': '29%',
  'Longwood': '47%',
  'Loyola-Chi': '40%',
  'LSU': '31%',
  'Marquette': '33%',
  'Memphis': '34%',
  'Miami FL': '39%',
  'Michigan': '38%',
  'Michigan St': '37%',
  'Montana St': '41%',
  'Murray St': '36%',
  'N Mex St': '43%',
  'Norfolk St': '54%',
  'N Carolina': '37%',
  'Notre Dame': '38%',
  'Ohio St': '33%',
  'Providence': '32%',
  'Purdue': '37%',
  'Richmond': '37%',
  'Rutgers': '34%',
  'S Dakota St': '41%',
  'San Diego St': '31%',
  'San Fran': '36%',
  'Seton Hall': '37%',
  "St Mary's": '30%',
  "St Peter's": '47%',
  'TAM C. Christi': '58%',
  'TCU': '35%',
  'Tennessee': '27%',
  'Texas': '34%',
  'Texas Tech': '30%'},
 'UAB': {'UCLA': '40%',
  'USC': '42%',
  'Vermont': '54%',
  'Villanova': '31%',
  'Virginia Tech': '40%',
  'Wisconsin': '43%',
  'Wright St': '61%',
  'Wyoming': '49%',
  'Yale': '62%',
  'Akron': '74%',
  'Alabama': '46%',
  'Arizona': '33%',
  'Arkansas': '37%',
  'Auburn': '31%',
  'Baylor': '36%',
  'Boise St': '40%',
  'Bryant': '70%',
  'Chatt': '52%',
  'Colgate': '65%',
  'Colo St': '43%',
  'Connecticut': '42%',
  'Creighton': '51%',
  'CS Fullerton': '78%',
  'Davidson': '38%',
  'Delaware': '71%',
  'Duke': '40%',
  'Georgia St': '76%',
  'Gonzaga': '37%',
  'Houston': '43%',
  'Illinois': '48%',
  'Indiana': '46%',
  'Iowa': '43%',
  'Iowa St': '50%',
  'Jville St': '74%',
  'Kansas': '36%',
  'Kentucky': '34%',
  'Longwood': '75%',
  'Loyola-Chi': '47%',
  'LSU': '45%',
  'Marquette': '45%',
  'Memphis': '43%',
  'Miami FL': '44%',
  'Michigan': '50%',
  'Michigan St': '50%',
  'Montana St': '68%',
  'Murray St': '49%',
  'N Mex St': '67%',
  'Norfolk St': '76%',
  'N Carolina': '55%',
  'Notre Dame': '54%',
  'Ohio St': '50%',
  'Providence': '47%',
  'Purdue': '47%',
  'Richmond': '56%',
  'Rutgers': '51%',
  'S Dakota St': '59%',
  'San Diego St': '50%',
  'San Fran': '51%',
  'Seton Hall': '57%',
  "St Mary's": '44%',
  "St Peter's": '72%',
  'TAM C. Christi': '76%',
  'TCU': '51%',
  'Tennessee': '36%',
  'Texas': '52%',
  'Texas Tech': '37%',
  'TX Southern': '75%'},
 'UCLA': {'USC': '60%',
  'Vermont': '59%',
  'Villanova': '50%',
  'Virginia Tech': '59%',
  'Wisconsin': '50%',
  'Wright St': '65%',
  'Wyoming': '58%',
  'Yale': '70%',
  'Akron': '77%',
  'Alabama': '50%',
  'Arizona': '45%',
  'Arkansas': '54%',
  'Auburn': '44%',
  'Baylor': '35%',
  'Boise St': '55%',
  'Bryant': '74%',
  'Chatt': '52%',
  'Colgate': '73%',
  'Colo St': '54%',
  'Connecticut': '49%',
  'Creighton': '50%',
  'CS Fullerton': '79%',
  'Davidson': '61%',
  'Delaware': '75%',
  'Duke': '44%',
  'Georgia St': '78%',
  'Gonzaga': '40%',
  'Houston': '46%',
  'Illinois': '58%',
  'Indiana': '71%',
  'Iowa': '54%',
  'Iowa St': '64%',
  'Jville St': '75%',
  'Kansas': '37%',
  'Kentucky': '39%',
  'Longwood': '76%',
  'Loyola-Chi': '59%',
  'LSU': '63%',
  'Marquette': '60%',
  'Memphis': '59%',
  'Miami FL': '63%',
  'Michigan': '58%',
  'Michigan St': '55%',
  'Montana St': '73%',
  'Murray St': '57%',
  'N Mex St': '63%',
  'Norfolk St': '79%',
  'N Carolina': '61%',
  'Notre Dame': '67%',
  'Ohio St': '69%',
  'Providence': '55%',
  'Purdue': '41%',
  'Richmond': '58%',
  'Rutgers': '64%',
  'S Dakota St': '66%',
  'San Diego St': '52%',
  'San Fran': '52%',
  'Seton Hall': '60%',
  "St Mary's": '46%',
  "St Peter's": '78%',
  'TAM C. Christi': '79%',
  'TCU': '61%',
  'Tennessee': '38%',
  'Texas': '69%',
  'Texas Tech': '42%',
  'TX Southern': '74%',
  'UAB': '59%'},
 'USC': {'Vermont': '57%',
  'Villanova': '33%',
  'Virginia Tech': '42%',
  'Wisconsin': '48%',
  'Wright St': '61%',
  'Wyoming': '59%',
  'Yale': '68%',
  'Akron': '74%',
  'Alabama': '44%',
  'Arizona': '32%',
  'Arkansas': '37%',
  'Auburn': '34%',
  'Baylor': '36%',
  'Boise St': '34%',
  'Bryant': '73%',
  'Chatt': '57%',
  'Colgate': '67%',
  'Colo St': '36%',
  'Connecticut': '41%',
  'Creighton': '52%',
  'CS Fullerton': '72%',
  'Davidson': '53%',
  'Delaware': '69%',
  'Duke': '41%',
  'Georgia St': '71%',
  'Gonzaga': '34%',
  'Houston': '37%',
  'Illinois': '43%',
  'Indiana': '53%',
  'Iowa': '41%',
  'Iowa St': '49%',
  'Jville St': '69%',
  'Kansas': '33%',
  'Kentucky': '35%',
  'Longwood': '69%',
  'Loyola-Chi': '51%',
  'LSU': '50%',
  'Marquette': '44%',
  'Memphis': '48%',
  'Miami FL': '52%',
  'Michigan': '45%',
  'Michigan St': '45%',
  'Montana St': '67%',
  'Murray St': '53%',
  'N Mex St': '61%',
  'Norfolk St': '73%',
  'N Carolina': '50%',
  'Notre Dame': '57%',
  'Ohio St': '42%',
  'Providence': '38%',
  'Purdue': '37%',
  'Richmond': '55%',
  'Rutgers': '55%',
  'S Dakota St': '65%',
  'San Diego St': '45%',
  'San Fran': '43%',
  'Seton Hall': '44%',
  "St Mary's": '41%',
  "St Peter's": '75%',
  'TAM C. Christi': '72%',
  'TCU': '50%',
  'Tennessee': '31%',
  'Texas': '47%',
  'Texas Tech': '36%',
  'TX Southern': '74%',
  'UAB': '57%',
  'UCLA': '39%'},
 'Vermont': {'Villanova': '31%',
  'Virginia Tech': '32%',
  'Wisconsin': '38%',
  'Wright St': '56%',
  'Wyoming': '48%',
  'Yale': '51%',
  'Akron': '63%',
  'Alabama': '50%',
  'Arizona': '41%',
  'Arkansas': '38%',
  'Auburn': '42%',
  'Baylor': '37%',
  'Boise St': '38%',
  'Bryant': '66%',
  'Chatt': '48%',
  'Colgate': '65%',
  'Colo St': '37%',
  'Connecticut': '44%',
  'Creighton': '49%',
  'CS Fullerton': '62%',
  'Davidson': '42%',
  'Delaware': '61%',
  'Duke': '33%',
  'Georgia St': '62%',
  'Gonzaga': '38%',
  'Houston': '40%',
  'Illinois': '46%',
  'Indiana': '43%',
  'Iowa': '40%',
  'Iowa St': '45%',
  'Jville St': '63%',
  'Kansas': '38%',
  'Kentucky': '33%',
  'Longwood': '63%',
  'Loyola-Chi': '50%',
  'LSU': '45%',
  'Marquette': '40%',
  'Memphis': '48%',
  'Miami FL': '46%',
  'Michigan': '42%',
  'Michigan St': '41%',
  'Montana St': '60%',
  'Murray St': '42%',
  'N Mex St': '58%',
  'Norfolk St': '68%',
  'N Carolina': '45%',
  'Notre Dame': '47%',
  'Ohio St': '42%',
  'Providence': '41%',
  'Purdue': '43%',
  'Richmond': '50%',
  'Rutgers': '43%',
  'S Dakota St': '52%',
  'San Diego St': '40%',
  'San Fran': '46%',
  'Seton Hall': '45%',
  "St Mary's": '42%',
  "St Peter's": '61%',
  'TAM C. Christi': '69%',
  'TCU': '42%',
  'Tennessee': '35%',
  'Texas': '40%',
  'Texas Tech': '35%',
  'TX Southern': '63%',
  'UAB': '45%',
  'UCLA': '40%',
  'USC': '42%'},
 'Villanova': {'Virginia Tech': '63%',
  'Wisconsin': '65%',
  'Wright St': '63%',
  'Wyoming': '65%',
  'Yale': '70%',
  'Akron': '79%',
  'Alabama': '59%',
  'Arizona': '46%',
  'Arkansas': '64%',
  'Auburn': '55%',
  'Baylor': '46%',
  'Boise St': '62%',
  'Bryant': '71%',
  'Chatt': '70%',
  'Colgate': '74%',
  'Colo St': '61%',
  'Connecticut': '59%',
  'Creighton': '68%',
  'CS Fullerton': '79%',
  'Davidson': '73%',
  'Delaware': '77%',
  'Duke': '49%',
  'Georgia St': '73%',
  'Gonzaga': '38%',
  'Houston': '50%',
  'Illinois': '64%',
  'Indiana': '76%',
  'Iowa': '57%',
  'Iowa St': '72%',
  'Jville St': '76%',
  'Kansas': '52%',
  'Kentucky': '44%',
  'Longwood': '75%',
  'Loyola-Chi': '63%',
  'LSU': '59%',
  'Marquette': '67%',
  'Memphis': '67%',
  'Miami FL': '69%',
  'Michigan': '65%',
  'Michigan St': '62%',
  'Montana St': '76%',
  'Murray St': '64%',
  'N Mex St': '74%',
  'Norfolk St': '76%',
  'N Carolina': '65%',
  'Notre Dame': '77%',
  'Ohio St': '73%',
  'Providence': '65%',
  'Purdue': '54%',
  'Richmond': '69%',
  'Rutgers': '69%',
  'S Dakota St': '67%',
  'San Diego St': '64%',
  'San Fran': '64%',
  'Seton Hall': '71%',
  "St Mary's": '55%',
  "St Peter's": '77%',
  'TAM C. Christi': '73%',
  'TCU': '69%',
  'Tennessee': '51%',
  'Texas': '65%',
  'Texas Tech': '50%',
  'TX Southern': '76%',
  'UAB': '68%',
  'UCLA': '49%',
  'USC': '66%',
  'Vermont': '68%'},
 'Virginia Tech': {'Wisconsin': '43%',
  'Wright St': '65%',
  'Wyoming': '56%',
  'Yale': '69%',
  'Akron': '68%',
  'Alabama': '50%',
  'Arizona': '35%',
  'Arkansas': '40%',
  'Auburn': '35%',
  'Baylor': '31%',
  'Boise St': '33%',
  'Bryant': '67%',
  'Chatt': '66%',
  'Colgate': '64%',
  'Colo St': '44%',
  'Connecticut': '45%',
  'Creighton': '52%',
  'CS Fullerton': '67%',
  'Davidson': '59%',
  'Delaware': '68%',
  'Duke': '36%',
  'Georgia St': '72%',
  'Gonzaga': '34%',
  'Houston': '41%',
  'Illinois': '47%',
  'Indiana': '54%',
  'Iowa': '41%',
  'Iowa St': '62%',
  'Jville St': '69%',
  'Kansas': '32%',
  'Kentucky': '32%',
  'Longwood': '63%',
  'Loyola-Chi': '63%',
  'LSU': '49%',
  'Marquette': '55%',
  'Memphis': '51%',
  'Miami FL': '63%',
  'Michigan': '51%',
  'Michigan St': '48%',
  'Montana St': '64%',
  'Murray St': '52%',
  'N Mex St': '65%',
  'Norfolk St': '68%',
  'N Carolina': '51%',
  'Notre Dame': '64%',
  'Ohio St': '52%',
  'Providence': '43%',
  'Purdue': '39%',
  'Richmond': '63%',
  'Rutgers': '58%',
  'S Dakota St': '65%',
  'San Diego St': '40%',
  'San Fran': '51%',
  'Seton Hall': '51%',
  "St Mary's": '43%',
  "St Peter's": '69%',
  'TAM C. Christi': '65%',
  'TCU': '51%',
  'Tennessee': '29%',
  'Texas': '47%',
  'Texas Tech': '34%',
  'TX Southern': '68%',
  'UAB': '59%',
  'UCLA': '40%',
  'USC': '57%',
  'Vermont': '67%',
  'Villanova': '36%'},
 'Wisconsin': {'Wright St': '65%',
  'Wyoming': '65%',
  'Yale': '68%',
  'Akron': '74%',
  'Alabama': '48%',
  'Arizona': '47%',
  'Arkansas': '48%',
  'Auburn': '44%',
  'Baylor': '46%',
  'Boise St': '45%',
  'Bryant': '67%',
  'Chatt': '58%',
  'Colgate': '66%',
  'Colo St': '57%',
  'Connecticut': '43%',
  'Creighton': '52%',
  'CS Fullerton': '78%',
  'Davidson': '61%',
  'Delaware': '72%',
  'Duke': '47%',
  'Georgia St': '71%',
  'Gonzaga': '41%',
  'Houston': '46%',
  'Illinois': '44%',
  'Indiana': '68%',
  'Iowa': '40%',
  'Iowa St': '64%',
  'Jville St': '72%',
  'Kansas': '38%',
  'Kentucky': '43%',
  'Longwood': '70%',
  'Loyola-Chi': '49%',
  'LSU': '46%',
  'Marquette': '61%',
  'Memphis': '53%',
  'Miami FL': '66%',
  'Michigan': '48%',
  'Michigan St': '44%',
  'Montana St': '70%',
  'Murray St': '52%',
  'N Mex St': '67%',
  'Norfolk St': '76%',
  'N Carolina': '56%',
  'Notre Dame': '72%',
  'Ohio St': '58%',
  'Providence': '59%',
  'Purdue': '44%',
  'Richmond': '62%',
  'Rutgers': '67%',
  'S Dakota St': '68%',
  'San Diego St': '48%',
  'San Fran': '49%',
  'Seton Hall': '62%',
  "St Mary's": '42%',
  "St Peter's": '74%',
  'TAM C. Christi': '73%',
  'TCU': '57%',
  'Tennessee': '39%',
  'Texas': '56%',
  'Texas Tech': '43%',
  'TX Southern': '70%',
  'UAB': '56%',
  'UCLA': '49%',
  'USC': '51%',
  'Vermont': '61%',
  'Villanova': '34%',
  'Virginia Tech': '56%'},
 'Wright St': {'Wyoming': '29%',
  'Yale': '40%',
  'Akron': '46%',
  'Alabama': '37%',
  'Arizona': '29%',
  'Arkansas': '29%',
  'Auburn': '30%',
  'Baylor': '30%',
  'Boise St': '30%',
  'Bryant': '62%',
  'Chatt': '41%',
  'Colgate': '51%',
  'Colo St': '31%',
  'Connecticut': '33%',
  'Creighton': '36%',
  'CS Fullerton': '45%',
  'Davidson': '35%',
  'Delaware': '43%',
  'Duke': '29%',
  'Georgia St': '54%',
  'Gonzaga': '31%',
  'Houston': '34%',
  'Illinois': '35%',
  'Indiana': '38%',
  'Iowa': '32%',
  'Iowa St': '38%',
  'Jville St': '56%',
  'Kansas': '27%',
  'Kentucky': '28%',
  'Longwood': '52%',
  'Loyola-Chi': '42%',
  'LSU': '37%',
  'Marquette': '35%',
  'Memphis': '36%',
  'Miami FL': '35%',
  'Michigan': '37%',
  'Michigan St': '34%',
  'Montana St': '47%',
  'Murray St': '37%',
  'N Mex St': '42%',
  'Norfolk St': '61%',
  'N Carolina': '41%',
  'Notre Dame': '40%',
  'Ohio St': '38%',
  'Providence': '32%',
  'Purdue': '32%',
  'Richmond': '35%',
  'Rutgers': '37%',
  'S Dakota St': '46%',
  'San Diego St': '33%',
  'San Fran': '35%',
  'Seton Hall': '37%',
  "St Mary's": '30%',
  "St Peter's": '52%',
  'TAM C. Christi': '65%',
  'TCU': '38%',
  'Tennessee': '30%',
  'Texas': '42%',
  'Texas Tech': '31%',
  'TX Southern': '59%',
  'UAB': '38%',
  'UCLA': '34%',
  'USC': '38%',
  'Vermont': '43%',
  'Villanova': '36%',
  'Virginia Tech': '34%',
  'Wisconsin': '34%'},
 'Wyoming': {'Yale': '66%',
  'Akron': '67%',
  'Alabama': '41%',
  'Arizona': '34%',
  'Arkansas': '37%',
  'Auburn': '33%',
  'Baylor': '34%',
  'Boise St': '31%',
  'Bryant': '62%',
  'Chatt': '49%',
  'Colgate': '64%',
  'Colo St': '34%',
  'Connecticut': '38%',
  'Creighton': '38%',
  'CS Fullerton': '72%',
  'Davidson': '43%',
  'Delaware': '63%',
  'Duke': '41%',
  'Georgia St': '68%',
  'Gonzaga': '34%',
  'Houston': '38%',
  'Illinois': '34%',
  'Indiana': '40%',
  'Iowa': '39%',
  'Iowa St': '45%',
  'Jville St': '66%',
  'Kansas': '32%',
  'Kentucky': '32%',
  'Longwood': '67%',
  'Loyola-Chi': '52%',
  'LSU': '34%',
  'Marquette': '35%',
  'Memphis': '38%',
  'Miami FL': '42%',
  'Michigan': '44%',
  'Michigan St': '34%',
  'Montana St': '69%',
  'Murray St': '48%',
  'N Mex St': '59%',
  'Norfolk St': '71%',
  'N Carolina': '42%',
  'Notre Dame': '52%',
  'Ohio St': '37%',
  'Providence': '36%',
  'Purdue': '36%',
  'Richmond': '44%',
  'Rutgers': '51%',
  'S Dakota St': '49%',
  'San Diego St': '37%',
  'San Fran': '49%',
  'Seton Hall': '41%',
  "St Mary's": '42%',
  "St Peter's": '66%',
  'TAM C. Christi': '71%',
  'TCU': '43%',
  'Tennessee': '27%',
  'Texas': '44%',
  'Texas Tech': '34%',
  'TX Southern': '64%',
  'UAB': '50%',
  'UCLA': '41%',
  'USC': '40%',
  'Vermont': '51%',
  'Villanova': '34%',
  'Virginia Tech': '43%',
  'Wisconsin': '34%',
  'Wright St': '70%'},
 'Yale': {'Akron': '48%',
  'Alabama': '34%',
  'Arizona': '25%',
  'Arkansas': '25%',
  'Auburn': '24%',
  'Baylor': '28%',
  'Boise St': '26%',
  'Bryant': '57%',
  'Chatt': '35%',
  'Colgate': '40%',
  'Colo St': '27%',
  'Connecticut': '29%',
  'Creighton': '34%',
  'CS Fullerton': '60%',
  'Davidson': '37%',
  'Delaware': '42%',
  'Duke': '28%',
  'Georgia St': '57%',
  'Gonzaga': '27%',
  'Houston': '35%',
  'Illinois': '31%',
  'Indiana': '33%',
  'Iowa': '27%',
  'Iowa St': '33%',
  'Jville St': '45%',
  'Kansas': '26%',
  'Kentucky': '27%',
  'Longwood': '42%',
  'Loyola-Chi': '47%',
  'LSU': '29%',
  'Marquette': '31%',
  'Memphis': '28%',
  'Miami FL': '34%',
  'Michigan': '37%',
  'Michigan St': '32%',
  'Montana St': '52%',
  'Murray St': '42%',
  'N Mex St': '39%',
  'Norfolk St': '52%',
  'N Carolina': '38%',
  'Notre Dame': '36%',
  'Ohio St': '31%',
  'Providence': '28%',
  'Purdue': '31%',
  'Richmond': '31%',
  'Rutgers': '25%',
  'S Dakota St': '49%',
  'San Diego St': '27%',
  'San Fran': '31%',
  'Seton Hall': '36%',
  "St Mary's": '30%',
  "St Peter's": '54%',
  'TAM C. Christi': '67%',
  'TCU': '30%',
  'Tennessee': '26%',
  'Texas': '33%',
  'Texas Tech': '27%',
  'TX Southern': '57%',
  'UAB': '37%',
  'UCLA': '29%',
  'USC': '31%',
  'Vermont': '48%',
  'Villanova': '29%',
  'Virginia Tech': '30%',
  'Wisconsin': '31%',
  'Wright St': '59%',
  'Wyoming': '33%'}}
